### ISSUE TITLE
Converting a Vec to a Slice sometimes causes dubble borrow

### ISSUE THREAD

**Issue by AharonSambol** [rust-lang/rust-clippy#10308]
### Summary

When I write this:
```rust
fn add1(vc: &mut Vec<usize>) {
    func1(vc, vc[0]);
}
fn func1(vc: &mut Vec<usize>, val: usize) {}
```
Clippy tells me that "writing &mut Vec instead of &mut [_] involves a new object where a slice will do".

However if I switch it to this:
```rust
fn add1(vc: &mut Vec<usize>) {
    func1(vc, vc[0]);
}
fn func1(vc: &mut [usize], val: usize) {}
```
I get "cannot borrow *vc as immutable because it is also borrowed as mutable [E0502]".

(I think the first example works because it triggers an implicit reborrow of vc, which apparently happens after processing all the parameter, or at least thats the answer I got from [StackOverflow][3])

[Link to working example][1] 

[Link to not working example][2]

  [1]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=afb1704ebdbf2c69be07dd7f027ce8cd
  [2]: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c1bf5aa7d8cd68220c0ae7ac8160c8b0
  [3]: https://stackoverflow.com/questions/75399832/why-does-passing-a-vector-work-but-not-a-slice

### Lint Name

`ptr_arg`

### Version

```text
rustc 1.65.0 (897e37553 2022-11-02)
binary: rustc
commit-hash: 897e37553bba8b42751c67658967889d11ecd120
commit-date: 2022-11-02
host: x86_64-unknown-linux-gnu
release: 1.65.0
LLVM version: 15.0.0
```

**Comment by Jarcho** [comment]
The error after the change is a result of two-phase borrowing, which allows an implicitly mutably borrowed value to be treated as an immutable borrow until the mutability is needed (after all the arguments have been evaluated). Custom `Deref` impls can't use this as they're ultimately just function calls, rather than something the compiler knows about.

The call site can be changed to index then call (e.g `let x = v[0]; f(v, x);`), or you can just ignore the lint.

There likely won't be changes for this as the lint is working as intended here, and detecting cases where the result adds an inconvenience to the call site is not trivial.

**Comment by AharonSambol** [comment]
Oh ok, thanks

**Comment by Jarcho** [comment]
Another solution is to change the argument order, which also avoids the issue.

**Comment by AharonSambol** [comment]
Thanks although I didn't have trouble fixing it, it's just a bit annoying to get a lint that breaks the code
