### ISSUE TITLE
Strange behavior re `#[allow(clippy::nonminimal_bool)]`

### ISSUE THREAD

**Issue by smoelius** [rust-lang/rust-clippy#10435]
### Summary

The first `allow` works, but the second doesn't. ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1d21f797f957ac969e4b0416469f5c61))
```rust
fn main() {
    let x = vec![0];
    let y = vec![1];
    let z = vec![2];

    #[allow(clippy::nonminimal_bool)]
    if !x.is_empty() && !(y.is_empty() || z.is_empty()) {
        println!("{}", line!());
    }

    #[allow(clippy::nonminimal_bool)]
    if !(x == [0]) {
        println!("{}", line!());
    }
}
```

### Reproducer

See above.

**Comment by blyxyas** [comment]
I asked for this weird behaviour in [the Rust Zulip chat](https://rust-lang.zulipchat.com/) and it seems to be caused because the lint sees the whole function instead of the individual `if` statements.

For someone encountering this bug, llogiq recommends putting the `#[allow]` attribute in the whole function (It would remove the bug).

I think solving this issue would need to remake a great part of the lint to work in a per-expression basis instead of a per-function one.

**Comment by blyxyas** [comment]
I've made a fix for this issue, but as this isn't an urgent issue I think waiting a few weeks to not saturate PR reviewers is the better choice.

**Comment by blyxyas** [comment]
Just to make sure that nobody works on this for nothing.
@rustbot claim

**Comment by smoelius** [comment]
Thanks, @blyxyas!
