### ISSUE TITLE
New Lint: `pointer_as_const_underscore`

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust-clippy#10587]
### What it does

As far as I know, every usage of `.as_ptr() as *const _` is overcomplicated, as it has a pointer (`.as_ptr()`) being casted to a pointer (`as *const _`). So `as_ptr() as *const _` would be equal to `.as_ptr()` ([Example of them being equal](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=336dae9cd37e1d35e19331535c070786)).

Even when they have the same result, [~19.1k files use this pattern](https://github.com/search?q=lang%3ARust+%2F%5Cw*.as_ptr%5C%28%5C%29+as+%5C*const+_%2F&type=code).

---

## Notes

- Similar to #10567, this could cause some issues (as one targets `as *const _` and the other one `.as_ptr() as *const _`)
- I used the common `.as_ptr()` here as an example, but the lint would include any function returning a pointer.
- While `.as_ptr() as *const _` = `.as_ptr()`, it isn't equal to just `as *const _`.

### Lint Name

`pointer_as_const_underscore` or `as_ptr_as_const_underscore`

### Advantage

Cleaner code

### Drawbacks

*None that I can think of.*

### Example

```rust
let a = "a";
let a_ptr = a.as_ptr() as *const _;
```

Could be written as:

```rust
let a = "a";
let a_ptr = a.as_ptr();
```

**Comment by Jarcho** [comment]
Those are only the same if type inference doesn't pick a new type. e.g.
```rust
let a = "a";
let a: *const u8 = a.as_ptr() as *const _;
```

**Comment by Centri3** [comment]
> Those are only the same if type inference doesn't pick a new type. e.g.
> 
> ```rust
> let a = "a";
> let a: *const u8 = a.as_ptr() as *const _;
> ```

That could be written as `let a = a.as_ptr().cast::<u8>()`, though, which is much easier to understand (at least IMO).

in the case of changing mutability, something like `let a = a.as_ptr().cast_mut()` would be used instead (there is `as_mut_ptr` for this purpose, but let's ignore that for the purpose of this example)

The only place `as *const` makes sense really anywhere is when `as_ptr` isn't available or `addr_of` doesn't work, since it's temporary, so maybe this could be extended to `as *const` overall?

@rustbot claim

**Comment by Centri3** [comment]
> so maybe this could be extended to as *const overall?

oh snap, just noticed this is already covered by #10567

**Comment by blyxyas** [comment]
Just noticed that `as *const _` in #10567, could also catch a pointer.
