### ISSUE TITLE
Spot misspellings

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust-clippy#10662]
### What it does

Feel free to close this issue down if you think it's a bad idea or too much work.

I think it could be useful for Clippy to look for a set of common English misspellings in code comments (and perhaps elsewhere).

### Lint Name

misspelled_comment and misspelled_identifier

### Category

style

### Advantage

Less typos in the code are part of the overal correctness I expect from good code.

### Drawbacks

It could require lot of work to be implemented, there are other languages beside English, there could be too many false positives, etc.

### Example

Some examples:

https://github.com/codespell-project/codespell

https://docs.devexpress.com/CodeRushForRoslyn/117202/static-code-analysis/spell-checker

**Comment by matthiaskrgr** [comment]
I personally don't think clippy is the right place for this since there are already language independent tools which do that (such as codespell) 
https://xkcd.com/927/

You can also just open your code in libreoffice and check even the grammar with languagetool for example :see_no_evil: 

These code-spelling tools are very hit-or-miss, codespell used to flag "crate" (create?) and "mut" (mute?) 200 times in every rust project that I threw it at but maybe that has improved in the meantime. 
Having to maintain ever-growing dictionaries and having to have discussions like "is this a valid misspelling we want to lint against", "I want to pass custom dictionaries via config", "I want to allow certain spellings via lint attributes.."  is probably too much work, and there are actually more interesting problems one could solve instead imo :upside_down_face:
