### ISSUE TITLE
New lint that forbids `!bool`

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust-clippy#10796]
### What it does

`!bool` is hard to see and can lead to possible logical misunderstands. Instead, `expr == false` should be preferable.

This is not just my opinion based on experience, other ppl also think the same way. To list a few:

* https://github.com/hashcat/hashcat#contributing
* https://eev.ee/blog/2016/12/01/lets-stop-copying-c/#_1

### Lint Name

neg_bool

### Category

restriction

### Example

```rust
let expr: bool = ...;
if !expr { ... }
```

Could be written as:

```rust
let expr: bool = ...;
if expr == false { ... }
```

**Comment by PatchMixolydic** [comment]
If only `bool`s were linted against, one could still use `!` on values of other types that implement `Not`:
```rust
let x = get_u8();
if !x == 0x80 { ... }
```

This lint could be generalized by recommending `Not::not`:
```rust
use core::ops::Not;

let x = get_u8();
if x.not() == 0x80 {}
```

As an additional benefit, this avoids direct comparisons to boolean literals, which some consider to be an indicator of poor code quality ([eslint](https://typescript-eslint.io/rules/no-unnecessary-boolean-literal-compare/), [SonarSource](https://rules.sonarsource.com/typescript/RSPEC-1125), [Clippy](https://rust-lang.github.io/rust-clippy/master/index.html#bool_comparison)). This lowers the chance that contributors will waste time trying to implement cleanups that would be prevented by this lint.

**Comment by c410-f3r** [comment]
Thank you @PatchMixolydic for your feedback. The `not` approach is very appealing even with the lack of `prelude` support and is one more option for end-users.

**Comment by Centri3** [comment]
If this suggests using `not` instead of `!`, I feel like this could also be extended to other operators in `std::ops`, like `BitAnd` and others. Maybe each individual operator could be disabled by default, but through clippy.toml could be enabled?

@c410-f3r, are you still working on this? this is very appealing imo, while I don't see much of a benefit for using `not` (at least most of the time, `matches!` is a good example of when I could see using it. I feel like a lint specifically to disallow negative `matches!` and suggest using `not` would be a good idea as well) there are others I could see being very beneficial, like maybe `Index` and `IndexMut` to be explicit about immutability.

**Comment by c410-f3r** [comment]
@Centri3 A PR was recently submitted to try to deal with the matter involving `bool`s but work on different operators for different expression types is an orthogonal subject IMO.
