### ISSUE TITLE
Expanding `lintcheck` dataset

### ISSUE THREAD

**Issue by blyxyas** [rust-lang/rust-clippy#10883]
The biggest Rust crates (the ones used in `lintcheck`) are very well made, they follow all general coding conventions.
So, checking a new lint on excellent crates isn't really useful. (Also,  not all crates exhibits all behaviours, so some lints can get 0 matches using `lintcheck`).

So, I suggest being more like [Crater](https://github.com/rust-lang/crater), `lintcheck`'s inspiration and getting maybe the 1000 most downloaded crates, or maybe 100 random crates and checking those, maybe even having a flag to set the number of crates to check (so it can also be run on low-end devices).

26 of the best crates are simply not enough, real world lints require real world examples

---

As a bonus, we should also include timings, to check Clippy's performance changes. Although Clippy doesn't focus in performance, it's pretty useful

**Comment by matthiaskrgr** [comment]
You can simply point it at a different `toml` which contains an arbitrary list of crates and that's basically it.
The problem  is not "running it against more crates", the problem is "triaging and analyzing the results on a regular basis, filtering out FPs and reporting them to the clippy team and actually getting them fixed". This can be quite time intensive especially since you are dealing with entire programs and finding out which weirdness of that trait or that struct actually causes clippy to trigger the lint can be quit tricky.


>Also, not all crates exhibits all behaviours,

Sometimes crate authors fix all the clippy warnings (how dare they!) but we can work around by picking a crate version of 2 years ago which is older that some of the lints we have. :D 


I had some CI job actually test a bigger number of crates and dump the logs into a git repo (so you can just "git diff" and see if there are new lint warnings since yesterday) here: https://github.com/matthiaskrgr/clippy-lintcheck
but it stopped working for some reason and I didn't have the time anymore to do maintenance on it.
Feel free to pick that back up if you want :slightly_smiling_face:
