### ISSUE TITLE
`clippy::arithmetic_side_effects` triggers on operations using `Wrapping<T>`

### ISSUE THREAD

**Issue by ritikmishra** [rust-lang/rust-clippy#11145]
### Summary

The documentation says that some types (specifically `Wrapping` and `Saturating`) will not trigger the lint since they are known to not have side effects on arithmetic operations

[[rust playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=685913a71a2c98baab34bdbe33daa4b7)

### Lint Name

arithmetic_side_effects

### Reproducer

I tried this code:

```rust
#![deny(clippy::arithmetic_side_effects)]

use std::num::Wrapping;
fn main() {
    let mut x: Wrapping<u32> = Wrapping(0_u32);
    
    x += 1;
}
```

I saw this happen:

```
    Checking playground v0.0.1 (/playground)
error: arithmetic operation that can potentially result in unexpected side-effects
 --> src/main.rs:7:5
  |
7 |     x += 1;
  |     ^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arithmetic_side_effects
note: the lint level is defined here
 --> src/main.rs:1:9
  |
1 | #![deny(clippy::arithmetic_side_effects)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not compile `playground` (bin "playground") due to previous error
```

I was not expecting the lint to be triggered in this case.

### Version

This issue was observed in the Rust playground with  

```text
clippy 0.1.72 (2023-07-11 993deaa)
```

**Comment by y21** [comment]
Looks like clippy only handles `Wrapping<T>` correctly if the left hand side and right hand side are of the same type (e.g. `x += Wrapping(1)` would not lint), but it breaks as soon as they're of different types like they are here.

It also looks like the trait impl `impl AddAssign<u32> Wrapping<u32>` has only existed since 1.60.0, which was released after the lint was implemented, so that might be why it doesn't handle this case correctly.
