### ISSUE TITLE
Wrong `if_same_then_else` lint error when having two different integer

### ISSUE THREAD

**Issue by YouKnow-sys** [rust-lang/rust-clippy#11213]
### Summary

if we call a trait method on two different integer type in a if else condition and specify the types like `0_u8`, `0u16` and... this lint will give us a error about both if and else are the same, when they're not...

### Lint Name

if_same_then_else

### Reproducer

I tried this code:

```rust
let test = if true { 0_u16.is_power_of_two() } else { 0_u8.is_power_of_two() };
```

I saw this happen:

```
error: this `if` has identical blocks
  --> src.rs:44:28
   |
44 |         let test = if true { 0_u16.is_power_of_two() } else { 0_u8.is_power_of_two() };
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: same as this
  --> src.rs:44:61
   |
44 |         let test = if true { 0_u16.is_power_of_two() } else { 0_u8.is_power_of_two() };
   |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                           
```

I didn't expected to see any lint error here because I'm calling this trait method on two different type.

### Version

```text
rustc 1.71.0 (8ede3aae2 2023-07-12)
binary: rustc
commit-hash: 8ede3aae28fe6e4d52b38157d7bfe0d3bceef225
commit-date: 2023-07-12
host: x86_64-pc-windows-msvc
release: 1.71.0
LLVM version: 16.0.5
```

**Comment by y21** [comment]
From a quick look, it seems like `SpanlessEq`'s way of checking if two integer literal expressions are equal is wrong because it disregards the types.

https://github.com/rust-lang/rust-clippy/blob/43577d58f96d95d80cfff206b33f6b2545139a19/clippy_utils/src/hir_utils.rs#L255-L264

Looks like it folds `0_u8` and `0_u16` to the constant 0 and concludes that the expressions must be equal
