### ISSUE TITLE
`extra_unused_type_parameters` + where clause requiring the parameter

### ISSUE THREAD

**Issue by urben1680** [rust-lang/rust-clippy#11302]
### Summary

When a generic parameter is mentioned in a where clause, Clippy seems to not notice that.
The suggestion of removing the parameter would result in non-compiling code.

The lint tries to protect the user from signatures where rustc cannot infer the type.

Here is the full example that also shows rustc can indeed infer the type of `Signature`:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=902fccc27c7495faca8e0863ba13486b

### Lint Name

extra_unused_type_parameters

### Reproducer (incomplete, full code above)

```rs
fn store<T: 'static, Signature: 'static>(v: &mut Vec<Box<dyn Closure>>, func: T)
where
    WrappedFn<T, Signature>: Closure,
{
    v.push(Box::new(WrappedFn {
        inner: func,
        _p: PhantomData,
    }));
}
```
```
warning: type parameter `Signature` goes unused in function definition
  --> src/main.rs:50:20
   |
50 | fn store<T: 'static, Signature: 'static>(v: &mut Vec<Box<dyn Closure>>, func: T)
   |                    ^^^^^^^^^^^^^^^^^^^^ help: consider removing the parameter
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_type_parameters
   = note: `#[warn(clippy::extra_unused_type_parameters)]` on by default
```

### Version

```text
Stable Playground with Rust 1.71.1
```

**Comment by mkrasnitski** [comment]
Here is a more minimal reproducing example:

```rust
use std::fmt::Debug;
use std::marker::PhantomData;

#[derive(Debug)]
struct Wrapper<T>(PhantomData<T>);

fn store<T: 'static>(v: &mut Vec<Box<dyn Debug>>)
where
    Wrapper<T>: Debug
{
    v.push(Box::new(Wrapper(PhantomData)));
}
```

The bug here is that the lint assumes that generic parameters can only appear on the left side of a where bound if they are directly bound, as in `where T: Copy`, but in this case, T appears as a concrete type by filling in the generic parameter for `Wrapper`. In this sense, it could be considered used. This should be pretty easy to fix.

I thought there might be another bug here related to the use of constructing `PhantomData` raw without specifying a type parameter, but this seems impossible to create without also specifying the `where Wrapper<T>: Debug` bound. Trying to remove the where bound causes type inference to fail, so I'm unsure if it's a real edge-case or not.
