### ISSUE TITLE
Suggested code causes error `(*b as usize)` -> `*b`

### ISSUE THREAD

**Issue by giluis** [rust-lang/rust-clippy#11968]
### Summary

Suggested code causes compilation error. See reproducer for details.

### Lint Name

clippy::unnecessary_cast

### Reproducer

I tried this code:

```rust
fn polynomial(nums: &[usize], degree: usize) -> impl FnOnce(usize) -> usize {
                                                                                                                 // suggests *b
    let A: Vec<_> = nums[0..=degree].iter().map(|b|(0..=degree).map(|p| ( *b as usize ).pow(p as u32)).collect::<Vec<_>>()).collect();
    let mut b= nums[0..=degree].to_vec();
    gaussian_elimination(A, &mut b);
    move |x| b.iter().enumerate().fold(0,|acc,(p,b)| acc + b*x.pow(p as u32))
}
```

I saw this happen:

![image](https://github.com/rust-lang/rust-clippy/assets/52404649/df34fe62-7606-41a9-a116-3b1803284c22)

I expected suggestion to be just `b`, rather than `*b`, since `*b` causes a compilation error, since `usize` cannot be dereferenced. 

### Version

```text
rustc 1.75.0-nightly (1c05d50c8 2023-10-21)
binary: rustc
commit-hash: 1c05d50c8403c56d9a8b6fb871f15aaa26fb5d07
commit-date: 2023-10-21
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.3
```

**Comment by ericwu2003** [comment]
Here's an example which I believe demonstrates this same bug:

```
fn compute_square(x: &usize) -> usize {
    (*x as usize).pow(2)
}
```
Clippy rightfully determines that the cast is redundant, and wants to remove it. However, the suggested source code is `*x.pow(2)` which does not compile, since the dereference is evaluated after the `pow` function, which returns `usize`.

Clippy should either suggest `x.pow(2)` or `(*x).pow(2)`
