### ISSUE TITLE
Can't disable new `struct_field_names` lint

### ISSUE THREAD

**Issue by ziimakc** [rust-lang/rust-clippy#12093]
### Description

New lint `struct_field_names` can't be disabled, while other rules are disabled fine when running `cargo clippy --fix --allow-dirty`.

Workspace root `Cargo.toml`:
```
[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
module_name_repetitions = "allow" # working
single_match_else = "allow" # working
future_not_send = "allow" # working
needless_pass_by_value = "allow" # working
struct_field_names = "allow" # not working
```

# Actual behavior: 
Warning:
```
6 |     pub user_id: Uuid,
  |     ^^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#struct_field_names
  = note: `-D clippy::struct-field-names` implied by `-D clippy::pedantic`
  = help: to override `-D clippy::pedantic` add `#[allow(clippy::struct_field_names)]`
```

# Expected

No warnings when `struct_field_names = "allow"`

### Version

```text
rustc 1.75.0 (82e1608df 2023-12-21)
binary: rustc
commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
commit-date: 2023-12-21
host: x86_64-unknown-linux-gnu
release: 1.75.0
LLVM version: 17.0.6
```

**Comment by ziimakc** [comment]
@y21 yes

**Comment by y21** [comment]
Quoting the [reference level explanation](https://rust-lang.github.io/rfcs/3389-manifest-lint.html#reference-level-explanation):

> Sort them by priority and then **an unspecified order within priority** that we may change in the future.

> On initial release, the sort will likely be **reverse alphabetical** which would cause all to be last, making it unlikely to do what the user wants which would raise awareness of the need for setting priority for all groups.

------------

If I sort your lint table in reverse alphabetical order I get: `struct_field_names`, `single_match_else`, `pedantic`, `nursery`, `needless_pass_by_value`. <sub>...</sub>

So, due to this unstable ordering that cargo currently uses, `struct_field_names` and `single_match_else` are placed behind `pedantic = "deny"` and thus get overridden by the later rules.

We can verify that this is true by running `cargo clippy --verbose`, which shows the rustc invocation, which includes the lint level arguments in the order that cargo sorted it:
```
rustc ... '--allow=clippy::struct_field_names' '--allow=clippy::single_match_else' '--deny=clippy::pedantic' '--deny=clippy::nursery' '--allow=clippy::needless_pass_by_value' '--allow=clippy::module_name_repetitions' '--allow=clippy::future_not_send' '--deny=clippy::all' ...
```

The default priority is 0, which is why using a priority of -1 for the pedantic group forces it to be in front of all the default lints.
