### ISSUE TITLE
Lintcheck never reports ICEs

### ISSUE THREAD

**Issue by y21** [rust-lang/rust-clippy#12185]
### Description

The log file that lintcheck creates after a run has an `### ICE` section at the end. However, I've *never* actually seen any entries in there.
To confirm this, I added a `panic!();` to some random `check_expr` function and it indeed doesn't report them.
It does however print `WARNING: bad exit status after checking ...`, which I've seen many times but have always ignored because I wasn't sure what that's about, but I suspect that that's the ICE. 

### Version

https://github.com/rust-lang/rust-clippy/commit/99423e8b30a5837adec3b987beb2099b432af007

### Additional Labels

@rustbot label +C-bug

**Comment by Jacherr** [comment]
After doing some digging around in the lintcheck code, I've boiled this down to the following issues:
- Lintcheck collects information from `stdout` in JSON format about what Clippy reported for a particular crate (https://github.com/rust-lang/rust-clippy/blob/master/lintcheck/src/main.rs#L431-L436). However, ICEs are not sent to `stdout`, but to `stderr`, which is not used for this purpose.
- ICEs are not reported in JSON format (and I'm not sure it's possible to report them as such). As a result, it is not possible to parse them using `Message::parse_stream(...)` the same way `stdout` is parsed.
- There is the potential to manually check for ICEs in `stderr` through string matching (i.e., `stdout.contains("panicked at")`) - however, constructing a `ClippyWarning` from this is not possible due to `Diagnostic`s being marked `#[non_exhaustive]`. We would need to first convert them to a JSON format and deserialize them from that.
- Lastly, it's not possible to return the ICEs without first turning them into a diagnostic, because the `run_clippy_lints` function only returns a `Vec<ClippyWarning>` which is the output of the parsed stream (https://github.com/rust-lang/rust-clippy/blob/master/lintcheck/src/main.rs#L314).

Either we need to rethink how ICEs are detected in lintcheck entirely, or somehow convert them to a format that can be parsed into a `ClippyWarning`.
