### ISSUE TITLE
Can we not get attribute from other crate?

### ISSUE THREAD

**Issue by surechen** [rust-lang/rust-clippy#12669]
### Description

As compiler-team are trying to not rely on attributes from extern crates. https://github.com/rust-lang/compiler-team/issues/505

I find clippy are doing this in some function like 'is_hir_ty_cfg_dependant'.

I think we can remove this. Can we do that?  

I'm willing to submit a PR to do this.

@flip1995  @xFrednet

**Comment by flip1995** [comment]
I'm not sure if I fully understand the ask here. Clippy needs to know if something is `cfg`ed for some lints. Otherwise Clippy will introduce a bunch of false positives. I don't know if there are any other external attributes, besides `cfg` and `cfg_attr` that we care about. 

One thing Clippy does - but I think this is unrelated - is to define attributes like `#[clippy::has_significant_drop]` which crates like `parking_lot` use to mark their types. If those types are then used in the crates Clippy is run on, Clippy checks if a type has this attribute.

**Comment by surechen** [comment]
> I'm not sure if I fully understand the ask here. Clippy needs to know if something is `cfg`ed for some lints. Otherwise Clippy will introduce a bunch of false positives. I don't know if there are any other external attributes, besides `cfg` and `cfg_attr` that we care about.
> 
> One thing Clippy does - but I think this is unrelated - is to define attributes like `#[clippy::has_significant_drop]` which crates like `parking_lot` use to mark their types. If those types are then used in the crates Clippy is run on, Clippy checks if a type has this attribute. (I think this is similar to what the `#[diagnostics]` namespace does)


Very detailed answer. Thank you very much. That is what I want to know.
