### ISSUE TITLE
Confusing message (empty attribute) in double_must_use

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust-clippy#13003]
### Summary

The double_must_use message is:

```
warning: this function has an empty `#[must_use]` attribute, but returns a type already marked as `#[must_use]`
```

However, I don't know what an 'empty attribute' is. I tried googling for the term, and nothing came up.

### Version

```text
rustc 1.79.0 (129f3b996 2024-06-10)
binary: rustc
commit-hash: 129f3b9964af4d4a709d1383930ade12dfe7c081
commit-date: 2024-06-10
host: x86_64-unknown-linux-gnu
release: 1.79.0
LLVM version: 18.1.7
```

**Comment by y21** [comment]
In the context of this lint, `#[must_use]` is empty, `#[must_use = "message"]` is not.
The lint only warns on the former since must_use with a message can add additional context for that specific function that the type's `#[must_use]` message does not have, in which case it would not be redundant.

Maybe it could say "this function has a `#[must_use]` attribute with no message, but returns a type already marked as `#[must_use]`"
