### ISSUE TITLE
link from the lint in the docs to the code

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1303]
The idea came up in the lint workshop at rustbeltrust

We could simply generate a github search link to the uppercase name of the lint

**Comment by mcarton** [comment]
What?

**Comment by oli-obk** [comment]
In the lint list ( https://github.com/Manishearth/rust-clippy#lints ) we link to the docs. The suggestion is to also link to the source code of the lint.

**Comment by mcarton** [comment]
Most users should not need this, and having two links in that already quite big table would be confusing :confused: 
Also, how do you define what the source code of a lint is?

**Comment by oli-obk** [comment]
I know, but it could be like the src link in rustdocs, just a small thing.

Well the source is the line where the lint name is mentioned ;)

**Comment by mcarton** [comment]
> where the lint name is mentioned

Which one?
If you mean [the one where the lint doc is defined](https://github.com/Manishearth/rust-clippy/blob/502416fa78fdb47e98e9983da5a101de49454b0a/clippy_lints/src/len_zero.rs#L31-L52), I think that's pretty useless, as the doc is on the wiki/the website. Otherwise, it's [not](https://github.com/Manishearth/rust-clippy/blob/502416fa78fdb47e98e9983da5a101de49454b0a/clippy_lints/src/len_zero.rs#L105) [unique](https://github.com/Manishearth/rust-clippy/blob/502416fa78fdb47e98e9983da5a101de49454b0a/clippy_lints/src/len_zero.rs#L139).

**Comment by oli-obk** [comment]
We can link to a github search url on the clippy repo, that'll list all the use sites

**Comment by Manishearth** [comment]
Y'all have a lint workshop? What's it all about? 😀

**Comment by oli-obk** [comment]
I taught ppl how to write clippy lints. But the wireless was down all the time, so it was hard. Also we have a lot of work ahead of us to improve the lint writing experience for new ppl. I've already got a few ideas that I'll explore.
