### ISSUE TITLE
 consider passing `--cfg test` by default

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#1436]
Posted by @durka in https://github.com/arcnmx/cargo-clippy/issues/12

>Regular cargo clippy doesn't check #[test] functions because it can't (the code is gone by the time the lints run). But if you do cargo clippy -- --cfg test it works. I wonder if there are any downsides to making this the default behavior.

>I guess this breaks people who have #[cfg(not(test))] on things. But perhaps cargo-clippy can support a --test flag which would be a bit shorter than -- --cfg test.

**Comment by llogiq** [comment]
I think test code needs not by necessity follow the same strict guidelines that clippy requires of other code. On the other hand there is certainly value in having clippy check tests, too, so I wouldn't rule it out.

The best way would be to somehow run both with and without `--cfg test`, collect the reports and quell duplicates before output. This would also reduce duplicates due to the library/binary divide.

**Comment by mathstuf** [comment]
Note that `-- --cfg test` fails if there are `dev-dependencies` since they aren't available with just the flag.

**Comment by kurnevsky** [comment]
It seems there is no good way to run clippy on tests anymore? Compiler plugin is deprecated and `--cfg test` won't work with `dev-dependencies`.

**Comment by elichai** [comment]
Is there any news about this?
I don't think it should be enabled by default but I do thing that `--cfg test` should use `dev-dependencies`

**Comment by mikerite** [comment]
Try invoking clippy as `cargo clippy --tests`.

**Comment by mathstuf** [comment]
@oli-obk This can be closed now I think.
