### ISSUE TITLE
Lint references to features not defined in Cargo.toml

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust-clippy#1614]
For example, a `#[cfg(feature = "blah")]` when `blah` isn't in the `[features]` or `[dependencies]` sections of Cargo.toml. This may require some people to put a `blah = []` thing in the `[features]` section but I think it'd be worthwhile as a warn-by-default.

**Comment by oli-obk** [comment]
Unfortunately this is nigh impossible due to the fact that cfgs are expanded before clippy has a chance to run. Also we do not have cargo metadata available. It could be in cargo clippy, but we'll have to decide to add such Lint's, since we've never done that before. We probably need to pass the data to the linting rustc instance through env cars, so it's not pretty either. Alternatively we can lint directly from cargo clippy by parsing the crate from there (maybe through syn?)

**Comment by jplatte** [comment]
I just learned there is a merged RFC for doing this in the compiler itself! This can probably be closed in favor of https://github.com/rust-lang/rust/issues/82450 🙂
