### ISSUE TITLE
Suggest get_mut() instead of lock() method on Mutex

### ISSUE THREAD

**Issue by kryptan** [rust-lang/rust-clippy#1765]
If you have `mut` reference to a [`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html) then [`get_mut`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.get_mut) method is more efficient than [`lock`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock) since it doesn't require locking. If clippy detects such situation it could suggest to use `get_mut` instead of `lock`.

**Comment by oli-obk** [comment]
You need to use `expr_ty` instead of `expr_ty_adjusted` on the `self` argument of the `lock` call and check whether it's a mutable reference or a name of something that's mutable.

We can't detect whether we have immutable ownership to the value. so `let foo = Mutex::new(...); foo.lock()....` won't trigger :(
