### ISSUE TITLE
Rust API Guideline: Function docs include panic conditions in "Panics" section

### ISSUE THREAD

**Issue by mcarton** [rust-lang/rust-clippy#1791]
Only for functions calling `panic!` and other known-panicky functions (eg. `Option::unwrap`).

As per [Function docs include error, panic, and safety considerations](https://rust-lang-nursery.github.io/api-guidelines/documentation.html#c-failure).

**Comment by dtolnay** [comment]
I think requiring this when calling known-panicky functions is extreme. Often something is unwrapped because it is expected to never fail. That's not something you can explain to the caller. "This function panics if... the code is wrong"?

Requiring a "Panics" section if the function uses specifically `panic!` would be good. If it can panic, it should be documented. If it can't panic, they should have used `unreachable!` instead.

**Comment by clarcharr** [comment]
Don't forget `assert!` and co. as well.

**Comment by dtolnay** [comment]
We also usually don't want to document panics in logic provided by the caller.

```rust
/// # Panics
///
/// This function panics if `T`'s implementation of `Display` panics.
pub fn print<T: Display>(t: T) {
    println!("{}", t.to_string());
}
```
