### ISSUE TITLE
catch unnecessary pass by values

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#21]
If we're just accessing fields and methods, pass by reference might make more sense. Maybe.

**Comment by llogiq** [comment]
The problem here is that some functions actually *should* pass by value. Those functions tend to be named `into_`-something, `drop` or `transmute`, among others. Perhaps using a whitelist of name patterns would suffice to weed out most false positives – we could then also advise to either access by ref or rename the function.

**Comment by birkenfeld** [comment]
Well, I would assume that the `into_` methods generally move out at least some parts of `self`.

But it's a good point that `into_` should always take by value, kind of a complement lint. (And `as_` and `to_` should take a reference.)

**Comment by llogiq** [comment]
@birkenfeld added an issue.

**Comment by camsteffen** [comment]
We now have `needless_pass_by_value`
