### ISSUE TITLE
Limit to specific package in workspace, also excluding its dependencies

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust-clippy#3025]
Running Clippy on a specific package in a workspace with `cargo clippy -p package_in_workspace` works, thanks to #2585. It appears, however, that this does not exclude dependency crates within the same workspace. So if these deps cause any Clippy errors, compilation will be aborted and the targeted package won’t be checked. That’s a hindrance for gradually resolving Clippy suggestions across a large code base in a workspace.

**Comment by oli-obk** [comment]
We're reusing `cargo check` infrastructure. Can you check whether `cargo check` has the same issue?

**Comment by sanmai-NL** [comment]
How could I best verify that? This suggests `cargo check` has the same issue, no?

```sh
cargo check -p package_in_workspace_2
```
```
   Compiling syn v0.14.8                                                                                                                     
   Compiling serde_derive v1.0.71
    Checking package_in_workspace_1 v0.1.0 (file:///path/to/package_in_workspace_1)
    Checking package_in_workspace_2 v0.1.0 (file:///path/to/package_in_workspace_2)
    Finished dev [unoptimized + debuginfo] target(s) in 12.36s
```

**Comment by magnonellie** [comment]
Is this issue being worked on? We currently can't run clippy on [Amethyst](https://github.com/amethyst/amethyst) because we have dependencies using experimental clippy features.

```
error[E0658]: scoped lint `clippy::len_without_is_empty` is experimental (see issue #44690)
   --> /home/ellie/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.14/src/lib.rs:136:9
    |
136 |         clippy::len_without_is_empty,
    |
```
... is just an example of one of the many errors we get by default.

If this is an unrelated error then I apologize but I would still be happy for someone to point me in the right direction :sweat_smile:

**Comment by hcpl** [comment]
@magnonellie I think you used `clippy` from stable which doesn't support `clippy::lint` syntax, only `lint`. Beta and nightly should support that now.

**Comment by mykmelez** [comment]
A workaround appears to be (assuming `PACKAGE` and `PATH_TO_PACKAGE` are set appropriately):

```
cargo clean
cargo check -p $PACKAGE
touch $PATH_TO_PACKAGE/src/lib.rs
cargo clippy -p $PACKAGE
```

I would have thought this would work:

```
cargo clean
cargo check -p $PACKAGE
cargo clean -p $PACKAGE
cargo clippy -p $PACKAGE
```

But clippy doesn't seem to check the package in that case (at least it doesn't warn me about any problems in it), even though `cargo clean` supposedly supports the `-p` flag.

**Comment by geigerzaehler** [comment]
`cargo check` suffers from the same problem. The problem is that cargo does not distinguish between local dependencies inside our outside of the workspace. For both `--cap-lints=allow` is not set like it is for remote dependencies. This results in `cargo check` complaining about all lints in local packages. See https://github.com/rust-lang/cargo/issues/5998
