### ISSUE TITLE
borrowed_box gives syntactically invalid suggestion

### ISSUE THREAD

**Issue by vks** [rust-lang/rust-clippy#3128]
It suggests `&mut Trait + 'a`, which is invalid syntax. It should be `&mut (Trait + 'a)` instead.

**Comment by phansch** [comment]
Thank you for the report!
Could you provide a small code snippet that produces the lint with the incorrect suggestion? You can use [play.rust-lang.org](https://play.rust-lang.org/) which has Clippy available under 'Tools' on the right.

**Comment by logannc** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=07873a52c9615f8f6b6ba782fdf3e9fe

It isn't really an incorrect suggestion so much that if you do it verbatim it cannot possibly compile due to rustc parsing limitations. Though it can also require changing the callsite which may or may not be unwanted for this lint.

**Comment by mati865** [comment]
@logannc it builds and applying clippy suggestion causes compiler error similar to OP's. Therefore that's good example, thanks!

**Comment by mgr-inz-rafal** [comment]
I just stumbled upon the same issue, here's one more link to the playground :)

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1f119c4d2e02176783b3106b0ca743b7

**Comment by ThibsG** [comment]
Weird but it seems that the lint doesn't trigger anymore, can anyone confirm? Same for #3971 no?

**Comment by rail-rain** [comment]
I believe it's because of the lint now ignores every mutable references (#5491), and both of the two playground link uses mutable references. However, this issue is actually unrelated to mutability. It happens when the trait objects have auto traits or lifetime bounds.

[playground link that uses an immutable reference](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9af68de8fb8379c4b094706e23abfea0)

**Comment by rail-rain** [comment]
@rust-lang/clippy. I think you'd better reopen this issue.
