### ISSUE TITLE
False positive: `doc_markdown` on numbers.

### ISSUE THREAD

**Issue by devonhollowood** [rust-lang/rust-clippy#3299]
While implementing #3298, I ran into what I believe is a false positive for `doc_markdown`, where it marks "1_000_000_000" as [needing backticks](https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/excessive_precision.rs#L112-L113). Because a number doesn't refer to an identifier, I don't believe clippy should suggest backticks here.

I guess the counter argument is that numbers are only formatted with backticks in code, and thus any number formatted with backticks is a piece of code and should thus be formatted as such in the docs. If the `clippy` maintainers decide that is the case, I'll close this issue and go edit #3298 to add the backticks.

version: `clippy 0.0.212 (32b1d1fc 2018-10-05)`

**Comment by flip1995** [comment]
The `doc_markdown` lint should only lint on numbers with a `_` in them. I think if you write `1_000` instead of 1,000 (or 1.000 depending on where you from), to separate the digits, you should put the number in backticks, because this is nothing you would write outside of programming and therefore it is "code".
