### ISSUE TITLE
add a lint for find_map

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/rust-clippy#3474]
There are a bunch of iterator chains that are clearer with the new `find_map`. Off the top of my head, `.find(_).map(_)` and `.filter_map(_).nex()`. I think clippy should have a lit for this like the `filter_map
` and `filter_next` lints.

**Comment by Areredify** [comment]
@flip1995 this one is long implemented too. (Also, should I always tag you in those issues or there are more appropriate channels?)

**Comment by flip1995** [comment]
Thanks! For Clippy I get notified for every comment/PR/issue/... anyway. Doesn't matter if I'm tagged or not. 

I first look at the notifications I'm mentioned in though (if the list is long). Since these kind of issues are low hanging fruits, because I just have to click on close and give you a ❤️ for triage-ing, you can keep tagging me 👍
