### ISSUE TITLE
unwrap_or_else lint for constants greatly decreases readability

### ISSUE THREAD

**Issue by marmistrz** [rust-lang/rust-clippy#3492]
Take the following code
```
let foo = String::from("null")
serde_json::to_string_pretty(&payload).unwrap_or_else(|_| "serialization failed".to_owned())
// The commented line triggers the unwrap_or with a function call lint
// serde_json::to_string_pretty(&payload).unwrap_or("serialization failed".to_owned())
```
In the second variant, the function call should optimized out by the compiler and using a closure decreases readability IMO.

**Comment by oli-obk** [comment]
The idea of `perf` lints is that we force the compiler to do the right thing instead of relying on optimizations.

Performance code and readable code are often at odds, in this case I don't see why a `|_|` would decrease readability strongly.

That said, I have often wanted a nice way to express the above, so maybe we should be thinking about an `unwrap_or_from` method that allows just passing a string literal to be heap allocated only if needed. Maybe even just change the `unwrap_or` method to be generic.

That's a discussion for a different place though (e.g. the internals forum)
