### ISSUE TITLE
Make VEC_BOX lint configurable over the size of T

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#3547]
In #3545 the `VEC_BOX` lint was implemented. This lints on usage of `Vec<Box<T: Sized>>` . The `Box` around `T` could make sense though, if `T` is a very large type. (See also https://github.com/rust-lang/rust-clippy/issues/3530#issuecomment-446058452)

A good enhancement for this lint would be, to make it configurable over the size of `T`, with some meaningful default value (TBD).

**Comment by udoprog** [comment]
Just wanted to echo this. I'm storing a lot of large objects in a Vec (~32G in total) and in order to meet memory constraints they need to be boxed. When the vector is at capacity requires the next capacity's worth of contiguous memory to move the values into. Also shuffling the pointers around has proven to be much more efficient.

So the `vec_box` lint is very noisy for me. Preferably I'd like to be able to mark the types for which it should be ignored.
