### ISSUE TITLE
New lint: replace `x.get(x.len()-1)` with `x.last()`

### ISSUE THREAD

**Issue by detrumi** [rust-lang/rust-clippy#3673]
The following can be replaced with `x.last()`:
```
let x = vec![1,2,3];
let _ = x.get(x.len() - 1);
```

**Comment by matthiaskrgr** [comment]
For a vector, `x.last()` returns `Option<T>` while `x[idx]` returns just `T` so it's not quite the same?

**Comment by detrumi** [comment]
Oh right, so it doesn't work for `x[x.len() - 1]` then.

**Comment by HarrisonMc555** [comment]
I think I could try to do this one (if nobody else is working on it). I'll try to be following the instructions in [CONTRIBUTING.md](https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md), but I assume I can ask here if I need more help?

**Comment by oli-obk** [comment]
>  I assume I can ask here if I need more help?

Yes always. Or on irc, or on discord.

**Comment by HarrisonMc555** [comment]
Ok so I think I have something working, but I can't manage to get the UI tests to run. Every time I try, it says `error: unknown clippy lint: clippy::use_last`. I ran `utils/dev update_lints` and I can see the changes in `clippy_lints/src/lib.rs`, but it still doesn't seem to be working.

I've tried looking around and haven't found anything. Any idea what's going on?

Here is the branch:

https://github.com/HarrisonMc555/rust-clippy/tree/use_last

Here is the UI test ([link](https://github.com/HarrisonMc555/rust-clippy/blob/864dfbdcf694dc6b56d55f6878b68c008599d504/tests/ui/use_last.rs)):

```rust
#![warn(clippy::use_last)] // This gives an error

fn dont_use_last() -> Option<i32> {
    let x = vec![2, 3, 5];
    let last_element = x.get(x.len() - 1); // ~ERROR Use _.last()
    last_element.map(|val| val + 1) // To avoid warnings
}

fn index_into_last() -> i32 {
    let x = vec![2, 3, 5];
    let last_element = x[x.len() - 1];
    last_element + 1 // To avoid warnings
}

fn main() {
    let expected_value: i32 = 5;
    assert_eq!(dont_use_last(), Some(expected_value));
    assert_eq!(index_into_last(), expected_value);
}
```

**Comment by flip1995** [comment]
You forget to add
```rust
reg.register_early_lint_pass(box foo_functions::FooFunctionsPass);
```
to `clippy_lints/src/lib.rs`.

After registering the lint it should produce output.

Currently in the making, but might be useful: #3824

**Comment by HarrisonMc555** [comment]
Awesome, thanks for your help! I used the automatic update script which added it to the complexity lists, etc., but didn't do this. Whoops.

I have one more question: how do I check to make sure that the vector that they're calling `get` on is the same as the one they're calling `len` on? I tried comparing the `hir_id` values and that didn't work. That makes sense, since that's an `Expr`, and the expressions are in different places.

However, when I matched on `my_struct_expr.node`, it was a `ExprKind::Path`. Can I compare these directly to see if they are the same things? I don't know how to check for identical "objects".

Thanks again for the help!
