### ISSUE TITLE
Lint wrong usage of known attributes - spotlight: no_std

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust-clippy#3782]
When compiling a `no_std` crate it already happened multiple times that I forgot the `!` after the `#` in `#![no_std]` (or similar) attribute specifiers making it a useless `#[no_std]` causing compilation troubles because I accidentally pulled std due to this. The compiler doesn't warn for misusage of known attributes like `no_std` and I am not sure if it should. But it would be awesome to have a `clippy` lint for this situation! Would have saved me hours of debugging already - **ashamed**.

**Comment by Manishearth** [comment]
This is surprising, the compiler errors (or used to error?) for this kind
of mistake in many cases.

But yeah we should def catch any cases like this in clippy, in case we
don't just make this a part of the compiler.

**Comment by phansch** [comment]
A similar lint is [`empty_line_after_outer_attr`](https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_outer_attr), but I think you had it directly above an item without any newlines, right?

**Comment by petrochenkov** [comment]
This should be an error from the compiler, yes.
We are currently lacking a centralized infra for reporting attributes applied to wrong targets though, so these errors are reported very irregularly.
I hope to implement something like https://github.com/rust-lang/rust/pull/57321, but for attribute targets, some time, so this may be fixed in rustc in the future.

**Comment by J-ZhengLi** [comment]
seems like it's handled by the `unused_attributes` lint in rustc (which came after this issue ofc~). 

So... closing it as its already done by the compiler.
