### ISSUE TITLE
Clippy is hangs forever when SIGKILLed

### ISSUE THREAD

**Issue by mchernyavsky** [rust-lang/rust-clippy#3890]
## Environment

* **Rustc:** 1.34.0-nightly (aadbc459b 2019-02-23)
* **Cargo:** 1.34.0-nightly (5c6aa46e6 2019-02-22)
* **Clippy:** 0.0.212 (d61b2541 2019-02-19)
* **Operating system:** macOS Mojave 10.14.3 (18D109)

## Problem description

(i'm not sure if this is the right issue tracker)

I'm trying to integrate Clippy as a linter "on the fly" for IntelliJ Rust. IntelliJ Rust already has such integration with `cargo check` -- when the user stops typing the IDE runs `cargo check` process in the background, waits for result, parses Cargo's JSON messages and highlights problem code. If the user starts typing before the `cargo check` process is finished, then the IDE kills just kills the process. So, I want to support Clippy in a similar way. ~On stable/beta toolchain everything works fine, but on nightly~ sometimes I encounter the following situation (IDE sends sigkill to the Clippy process tree and launch new Clippy instance, but it causes the 99774 process to hang forever and the new Clippy process is blocked on Cargo.lock):

<img width="600" alt="Activity Monitor" src="https://user-images.githubusercontent.com/6079006/54483636-be1e5100-4867-11e9-93c7-563c8a449cc2.png">

The cargo process (99774) sample:
https://gist.github.com/mchernyavsky/b5d24416add2916c00fe320ee2ef767d

**Comment by oli-obk** [comment]
Does this also happen for plain `cargo check`?

I don't really know how we could be causing something like that, but from the thread dump it looks like 2 threads are blocked on the third and the third is blocked on doing command line output. Maybe the killing also closes stderr/stdout, and if that happens during a particularly bad moment, the writing just freezes?

**Comment by mchernyavsky** [comment]
@oli-obk

> Maybe the killing also closes stderr/stdout

Yes, IDE closes this channels before sending sigkill.

> Does this also happen for plain `cargo check`?

I thought not, but now I managed to reproduce the problem with `cargo check` on stable. So I close the issue.

**Comment by Manishearth** [comment]
i had to

![image](https://user-images.githubusercontent.com/1617736/54493366-67773e00-488c-11e9-89b8-9ff145f0078d.png)

**Comment by matklad** [comment]
@mchernyavsky could re-open  this issue against Cargo repository, if possible, with a stand-alone reproduction. I fear like we might be hitting some nasty case.

From my understanding, what happens here is that the IDE communicates with `cargo` via pipe, then IDE closes the pipe, but Cargo hangs.

In theory, closing the pipe should cause the `println` to panic, because the underlying `write!` returns an EPIPE, because we ignore SIGPIPE [here](https://github.com/rust-lang/rust/blob/96d700f1b7bc9c53fa0d11567adb1ed2c1c27e79/src/libstd/sys/unix/mod.rs#L78). If it hangs, that means something's broken in stdlib.
