### ISSUE TITLE
We shouldn't strip blank comments in code in lint doc generation

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#4116]
See https://rust-lang.github.io/rust-clippy/master/index.html#empty_line_after_outer_attr

The blank lines in the source (important for this lint) are removed from the docs, since the doc generation step strips empty lines (before hitting any kind of markdown parser)

I'm not quite sure _why_ we do that at all, but we shouldn't be doing it within code.

(It's late so I haven't yet investigated)

**Comment by phansch** [comment]
This bug sounds vaguely familiar. I believe the bug is somewhere in https://github.com/rust-lang/rust-clippy/blob/cbae9ed8731d7ad8a167e1a779a881812bf14197/util/export.py#L19

or here:

https://github.com/rust-lang/rust-clippy/blob/cbae9ed8731d7ad8a167e1a779a881812bf14197/util/lintlib.py#L69-L72

For anyone investigating, `comment` in lintlib.py is called `doc` in `export.py`.
