### ISSUE TITLE
non_ascii_literal example should be more verbose

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust-clippy#4117]
Currently, the doc for [non_ascii_literal](https://rust-lang.github.io/rust-clippy/master/index.html#non_ascii_literal) isn't showing what to do better.

I think including a "Could be written:" example would be helpful. Just like clippy does in the console.

Instead of just `let x = "Hä?"`.
Something like this would be better.
```rust
 String::from("€");
    |         ^^^
    |
    = help: Consider replacing the string with:
            ""\u{20ac}""
```

I can make a PR, if someone tells me where I can find this lint :)

**Comment by flip1995** [comment]
You can find the documentation of this lint here:
https://github.com/rust-lang/rust-clippy/blob/58e12130e4e8976f16c87190b51d2e5748691536/clippy_lints/src/unicode.rs#L35-L38

---
If you want to do some extra work, to make the lint even better, you can change these `span_help_and_lint`:
https://github.com/rust-lang/rust-clippy/blob/58e12130e4e8976f16c87190b51d2e5748691536/clippy_lints/src/unicode.rs#L102-L115

with [`span_lint_and_sugg`](https://github.com/rust-lang/rust-clippy/blob/fd563810158425c20f27768da4ef54c54230bbbf/clippy_lints/src/utils/diagnostics.rs#L169-L177), so that the suggestion is displayed more idiomatically and is auto-fixable.

The `applicability` should me `MachineApplicable`.
