### ISSUE TITLE
AppVeyor runs redundant tests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust-clippy#4263]
Hi there! We are a bit contended for AppVeyor CI time in the rust rust-lang-libs group of projects (which is basically all of rust-lang and rust-lang-nursery except for rustc itself, and we all share a single parallel CI job). I noticed that clippy's configuration could be improved.

First of all, you are running CI on auto and master, which means that after bors tested the change on auto and pushes to master, it gets tested *again*. You can avoid this by adding the following to the beginning of your AppVeyor script (taken from cargo's config):
```
if NOT defined APPVEYOR_PULL_REQUEST_NUMBER if "%APPVEYOR_REPO_BRANCH%" == "master" appveyor exit
```

Secondly, consider how useful running AppVeyor on each PR (an each push to each PR at that) is. If you could live without that, you can remove `master` from the AppVeyor config entirely. You can still do try builds for on-demand Windows testing.

**Comment by flip1995** [comment]
> and each push to each PR at that

We already disabled that IIRC. But only running AppVeyor on try builds is a good suggestion. We already have a travis windows check, that runs on every PR. This is _allowed to fail_, since the windows build system still can't handle secrets, I think.

To run the travis job successfully though, the `clippy_workspace_test` needs to be fixed.

**Comment by RalfJung** [comment]
> We already disabled that IIRC.

That would be great! I can't find a trace of that though, and at https://ci.appveyor.com/project/rust-lang-libs/rust-clippy/history I see two full builds for every "auto merge" commit. So whatever you are doing does not seem to work?

**Comment by flip1995** [comment]
Oh I just meant AppVeyor on each push to a PR https://github.com/rust-lang/rust-clippy/commit/8d7a5fe126983e82caaf20be47841329131f15fa. Disabling it on master and auto only requires to remove the `master` and `auto` entry in the list.

IMO I would still run AppVeyor on r+ builds, since they only happen a few times a day (11 times in the last 5 days) and it's easy to miss changes that may affect windows builds and need a `try` run.

**Comment by RalfJung** [comment]
> Oh I just meant AppVeyor on each push to a PR 8d7a5fe.

PRs for master will still run AppVeyor on each push with this.

> IMO I would still run AppVeyor on r+ builds, since they only happen a few times a day (11 times in the last 5 days) and it's easy to miss changes that may affect windows builds and need a try run.

Sure, I never suggested to disable AppVeyor on auto/try.

**Comment by RalfJung** [comment]
Hm, but I don't see AppVeyor in your PRs. Seems I misinterpreted the AppVeyor config there -- so looks like once you do `branches: only:`, you just never get any PRs?

In that case, the only thing that's left to do here is remove `master` from the list. It serves literally no purpose I think.

**Comment by flip1995** [comment]
> Sure, I never suggested to disable AppVeyor on auto/try.

I misinterpreted your post then.

> Hm, but I don't see AppVeyor in your PRs.

Yeah the `branches: only:` thing is the branch where the commit was pushed, not the branch the PR aims at.

> the only thing that's left to do here is remove master from the list

All right, I'll do that right away.

**Comment by RalfJung** [comment]
Thanks!
