### ISSUE TITLE
Removing the exact lint count from the readme?

### ISSUE THREAD

**Issue by phansch** [rust-lang/rust-clippy#4390]
Addition and deprecation of multiple lints in a short period of time has regularly caused merge conflicts because of the exact lint count at the top of the README: `There are 310 lints included in this crate!`

Does anyone feel like the exact count is worth having?
Removing the exact count would mean less friction for contributors. 

I would probably just replace it with `There are over 300 lints included in this crate!`

**Comment by flip1995** [comment]
The lint count has to be updated in 
https://github.com/rust-lang/rust-clippy/blob/34457fbd8b0980e0d41e34372cb99f86490d07f7/src/lintlist/mod.rs#L9
anyway, so removing it from the README only partially resolves this problem. Also these were the first deprecations we had since the introduction of tool lints, so this doesn't happen that often.

This also happens when 2 PRs implement a new lint though. But then again, since the last stable release we got 3 new lints, so this doesn't happen that often either.

---
IMO the count in the README is really cool. But I don't think it would be that big of an issue if we remove it.

**Comment by BO41** [comment]
https://github.com/rust-lang/rust-clippy/blob/34457fbd8b0980e0d41e34372cb99f86490d07f7/src/lintlist/mod.rs#L9

is this type annotation really needed? Shouldn't it work without it?

**Comment by flip1995** [comment]
Yes, because `ALL_LINTS` is a constant and constants have the syntax
```
[pub] const Ident: Type = Expr;
```
where `: Type` is required.

**Comment by phansch** [comment]
> removing it from the README only partially resolves this problem

Oh, I hadn't thought of the lintlist, thanks for bringing it up!
I don't mind too much either way and was just hoping for some low hanging fruit :smile:
