### ISSUE TITLE
Suggestion for removing `to_string()` to `format!()`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust-clippy#4468]
Considering this code:

```rust
let s = format!("Hello, {}", "world").to_string();
```

This `to_string()` isn't needed because `format!` returns `String` type.
It'd be nice for Clippy to tell us it's needless.

**Comment by sinkuu** [comment]
`redundant_clone` contains general check for calling `to_string()` on `String` (just because it can be seen as cloning). It might better be extracted into another lint.

https://github.com/rust-lang/rust-clippy/blob/4c8a941dafff56a2485258b85b33ba33e66f6258/tests/ui/redundant_clone.stderr#L1-L12

**Comment by flip1995** [comment]
Yes, what @sinkuu said, this is already linted:
```rust
#[warn(clippy::redundant_clone)]
fn main() {
    let _s = format!("Hello, {}", "world").to_string();
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3ff38da21a5c45b0ad8af7c33311d448)

But the `redundant_clone` lint is in the nursery group, because https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone

So yeah maybe this could be extracted in a more restricted lint, that can be warn-by-default.

**Comment by flip1995** [comment]
`E-medium` if someone wants to attempt to fix this lint in itself.

**Comment by Shubhamchinda** [comment]
Hey. Can I take this?

**Comment by JohnTitor** [comment]
@Shubhamchinda go ahead!

**Comment by camsteffen** [comment]
`redunant_clone` is now in `perf` so this warns by default.
