### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust-clippy#4745]
There are currently [45 branches](https://github.com/rust-lang/rust-clippy/branches) at this repo. Most of them are old and outdated (see [staled branches](https://github.com/rust-lang/rust-clippy/branches/stale)). It would be nice if they can get removed so the git completion looks better (e.g. `git checkout <tab>`).

**Comment by flip1995** [comment]
I cleaned up a lot of branches, which PRs got merged, the commits in these branches got merged in another way (another PR, manually pushed, ...) or could be deleted savely for some other reasons.

There are 19 branches left.

ping @Manishearth @oli-obk Maybe the `rust-1.*` branches should be protected, like [rust-1.31.0](https://github.com/rust-lang/rust-clippy/tree/rust-1.31.0)

[beta1.35](https://github.com/rust-lang/rust-clippy/tree/beta1.35) should maybe renamed to `rust-1.35.0` or deleted, since there are no new commits in comparison to the master branch. @Manishearth 

[stable](https://github.com/rust-lang/rust-clippy/tree/stable) @Manishearth is this branch still required?

[beta_backport](https://github.com/rust-lang/rust-clippy/tree/beta_backport) @oli-obk is this branch still required?

[simplify_spanless_eq_usages](https://github.com/rust-lang/rust-clippy/tree/simplify_spanless_eq_usages) @oli-obk This seems like something you started over a year ago, but there never was a PR.

[ptr_arg_calls](https://github.com/rust-lang/rust-clippy/tree/ptr_arg_calls) @llogiq #2137 was closed, because
> I think it's safe to close this, as I no longer know what it should have done.

So I think this could be deleted?

[cow](https://github.com/rust-lang/rust-clippy/tree/cow) @llogiq 4 year old branch. Is there something in there you want to preserve?

[unused-files3](https://github.com/rust-lang/rust-clippy/tree/unused-files3) @fhahn The only commit on this branch is by you. The PR of this branch was `S-inactive-closed` and the GitHub user who opened it doesn't exist anymore.

[test-cov-travis](https://github.com/rust-lang/rust-clippy/tree/test-cov-travis) @mcarton I think this branch can be deleted?

[yati-sagade-master-506](https://github.com/rust-lang/rust-clippy/tree/yati-sagade-master-506) @mcarton I think this branch can be deleted?

**Comment by Manishearth** [comment]
I think the `stable` branch is actually `stable-somenumber`. as is `beta-backport`. We should protect those.

A think I tend to do is make empty merge commits to bring these branches into master's git history. Some of them may have already been merged and can be deleted.

**Comment by flip1995** [comment]
> A think I tend to do is make empty merge commits to bring these branches into master's git history

Ok I think this has already been done with `stable`, `beta1.35`, `rust-1.34.1`. `rust-1.31.0` and `beta_backport`, since these branches are 0 commits ahead of master. (?) `stable` and `rust-1.34.1` are exactly the same.

Should we do this also with the other branches or should we protect them?

**Comment by flip1995** [comment]
I just checked and #4109 includes all of the above mentioned branches. So can we delete these branches?

**Comment by Manishearth** [comment]
Yes, you can delete those branches as long as their head commit shows in git log.

**Comment by flip1995** [comment]
Each HEAD of these branches is in the master, so I deleted them. Except `rust-1.31.0`, since this branch is protected and I cannot unprotect it.

**Comment by Manishearth** [comment]
Deleted.

We should also probably create tags for the final published commit for each rust version.

**Comment by flip1995** [comment]
> We should also probably create tags for the final published commit for each rust version.

Done. I pushed the tags `rust-1.**.*` since 1.29.0, when Clippy was added to rustup.

**Comment by flip1995** [comment]
With `const-match` deleted after https://github.com/rust-lang/rust-clippy/pull/6215#issuecomment-849459585, we now only have branches necessary for CI, release, and deployment in this repo. @rust-lang/clippy please create your own fork and open PRs from there to keep it like this. (If you see the need to create a branch directly in this repo, please make sure to delete it right after the PR is merged or closed)
