### ISSUE TITLE
Lint request: Warn when importing inside a macro and not using the $ keyword.

### ISSUE THREAD

**Issue by nilscript** [rust-lang/rust-clippy#4798]
I suggest adding a lint for when a programmer makes a macro, imports something into said macro and forgets `$` before `crate` keyword. Exporting macros across crates can be a hassel, atleast for me.

**Comment by flip1995** [comment]
`E-hard`: It's really hard (maybe impossible) to determine if `use` statements refer to the current crate or some dependency. So doing this right is really hard.
`E-medium`:  A basic implementation (nursery/restriction lint), which triggers on every `use` statement inside a macro is possible. Currently no lint exists, which checks macro definitions, though. 

Macro definitions can be checked with [`EarlyLintPass::check_mac_def`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/lint/trait.EarlyLintPass.html#method.check_mac_def). 

The challenge here is, that only a `TokenStream` is available, instead of `AST` nodes.
