### ISSUE TITLE
Disable "on by default" notes

### ISSUE THREAD

**Issue by jwai0004** [rust-lang/rust-clippy#4819]
Is there a way to disable the "on by default" messages that appear below lints? For example:

![Screenshot from 2019-11-15 23-42-09](https://user-images.githubusercontent.com/43143052/68944274-9241d980-0801-11ea-8576-d135ebb80a51.png)

I would like to hide the line "note: `#[warn(clippy::assign_op_pattern)]` on by default"

I can find documentation on how to hide the further information link but not this note. Manually enabling the desired lints in the file or on the command line doesn't seem to remove this message.

**Comment by flip1995** [comment]
That is something rustc does: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15762f1500f786ee58ac2a02c5cd66ff)

This `note` only gets emitted on the first occurrence of a lint. There is currently no way to disable this.

FYI this message is added here: https://github.com/rust-lang/rust/blob/ab6e47851b51a413db5d721f25d714653e7549fd/src/librustc/lint/mod.rs#L715-L720

> Manually enabling the desired lints in the file or on the command line doesn't seem to remove this message

It should at least change the message, if you change the level on the command line or in the file

---

If you want this feature, please request it in rustc directly, since Clippy doesn't have access to this.
