### ISSUE TITLE
Lint suggestion: `unsafe` should require a `// Safety` comment

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust-clippy#4828]
I was pleased to see that there's a clippy lint for requiring a `/// # Safety` header in exposed unsafe methods; my suggestion is to go further and add a lint requiring safety commentary in all `unsafe { }` blocks.

**Comment by flip1995** [comment]
Normal comments `//` can't be checked by Clippy, since they are handled by the lexer and don't appear in the AST. Clippy can only check for Doc comments `///`. To lint this, Clippy would have to lex the code itself, which is something we really don't want to do (performance, code duplication, ...).

I'm closing this, since it is sadly not possible to accomplish. Sorry.

**Comment by Lucretiel** [comment]
Ah :( sad to hear, but I understand.
