### ISSUE TITLE
Warn on missing "Errors" section in docs for Result/Option returning methods.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust-clippy#4854]
Recently clippy added a warning for missing "Safety" sections in public `unsafe` methods/functions.

I'd like to see a similar thing for methods/functions that return Option or Result but don't have a "Errors" section in their doc.

(allow by default of course, we don't want to give people a heart attack)

**Comment by flip1995** [comment]
Referencing [Commonly Used Sections](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html?highlight=documentation#commonly-used-sections) of the rust book:

> **Errors**: If the function returns a Result, describing the kinds of errors that might occur and what conditions might cause those errors to be returned can be helpful to callers so they can write code to handle the different kinds of errors in different ways.

So we should suggest an `Error` section. Not sure if we should trigger this lint for `Option`, since this is not mentioned/recommended in the Rust book.

**Comment by RobbieClarken** [comment]
I'm keen to work on this issue if no-one else has picked it up.

**Comment by flip1995** [comment]
It's all yours. You can have a look at #4535 on how to go about implementing this.
