### ISSUE TITLE
lint against renaming of method arguments in trait impls

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust-clippy#486]
for consistency one should be using the same method arg names when implementing a trait as the ones used in the trait. 

possible cases:
- if the trait doesn't name them (`_`) an arbitrary name should be allowed,
- if the trait silences an unused warning in a default impl by prepending and underscore, allow the version without an underscore prefix
- allow prepending an underscore

**Comment by Manishearth** [comment]
I'm not sure how I feel about this lint, but okay as an `Allow` lint. Unsure about `Warn`.

(At some point we'll need to make a Rust RfC to figure out sensible defaults that the community agrees on.)

**Comment by fhartwig** [comment]
I would prefer this to be `Allow`. For most traits, this doesn't really matter since the methods only take `self` anyway, and for many of the others I don't think that consistency is important enough to warrant the cognitive overhead of remembering the exact argument names (quick, what's the name of the iterator argument to `Extend::extend`?)

**Comment by Manishearth** [comment]
(Well, clippy can give suggestions, so you don't need to look it up manually, but I agree in general)
