### ISSUE TITLE
Clippy ICE: normalize_erasing_regions: could not fully normalize `<Trait>::Assoc`

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust-clippy#4968]
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cdb7bc71b2a8f4b52bc6c239ea1965df)

```rust
trait Trait {
    type Assoc;
}

use std::{
    mem::{self, ManuallyDrop},
};

#[allow(unused)]
fn func<T: Trait>(slice: Vec<T::Assoc>) {
    unsafe {
        let _: Vec<ManuallyDrop<T::Assoc>> = mem::transmute(slice);
    }
}
```

This ICEs with `cargo clippy` but not with `cargo build` or `cargo check`.

**Comment by flip1995** [comment]
This crashes at [`normalize_ty_after_erasing_regions`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_traits/normalize_erasing_regions.rs.html#11-37), which is called by `TyCtxt::layout_of` here:

This is because [`At::normalize`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc/traits/query/normalize.rs.html#30-59) returns `Err(NoSolution)`.

One fix would be to check if the types given to 
https://github.com/rust-lang/rust-clippy/blob/c807fbc8ba41432388b6f590668ba81314c07c32/clippy_lints/src/transmute.rs#L641

are `TyKind::Projection` and bail out. But I'm not sure if that's to conservative.
