### ISSUE TITLE
[as_conversions] No alternative exists to float to/from int conversion using `as`

### ISSUE THREAD

**Issue by casey** [rust-lang/rust-clippy#5122]
The `as_conversions` lint warns if the `as` operator is used for int-to-float and float-to-int conversions, however I don't believe that there is actually an alternative.

It might be good to relax the lint so it doesn't complain if either argument is a float until an alternative exists.

**Comment by flip1995** [comment]
IMO it is an `restriction` lint, that should warn exactly about this. A float-to-int or int-to-float conversion is just such a dangerous conversion, that can be silently lossy. 
[Playgroun](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1dd42a3865a951beb497e64e2a8746fd) 

Allowing this, would defeat the purpose of this lint. For the cases, where `into`/`from` exists, we have the [cast_*](https://rust-lang.github.io/rust-clippy/master/index.html#cast) lints.

Side note: `restriction` lints are called like this, because they "restrict" the language, without claiming that the thing is per se bad. In this case the lint removes `as` from the language and therefore restricts the language.

**Comment by casey** [comment]
I think that's fair, but looking at the cast_* lints, it's not immediately obvious to me that there's a set of lints which would warn me about casts where a better alternative exists, i.e. `try_from` and `from`, but not warn me about casts where no alternative exists. Or am I not seeing it?

I.e. it seems reasonable to want `0u8 as 0u16` to be disallowed (`into` exists), `0u16 as 0u8` to be disallowed (`try_into` exists), but `u8 as f64` to be allowed, since there's no alternative, but no combination of lints can give you that.

**Comment by flip1995** [comment]
That is because an int-float-conversion has no alternatives, so we can't warn on `int as float` code, since it cannot be improved. This is where this lint comes into play. Just disallow every `as` conversion and if you are sure, that the conversion you're doing is save, add an `#[allow(...)]`. Kind of like `unsafe`.

**Comment by casey** [comment]
I guess that's reasonable. Thanks for the help!
