### ISSUE TITLE
New lint: using `#[macro_use]` instead of a `use` statement

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust-clippy#5179]
In the Rust 2018 edition, you can directly import exported macros via a normal `use` statement, instead of using the blanket `#[macro_use]` attribute. This makes it clear exactly which items you are importing, and avoids the need to use `extern crate`.

As far as I know, there are no cases where `#[macro_use]` works but `use some_crate::some_macro` doesn't.

**Comment by flip1995** [comment]
good first issue: just warning on `#[macro_use] use ...;`

Hard: finding the macros used by the import, and building an auto applicable suggestion.

**Comment by SOF3** [comment]
One known case is `diesel`. The code generated by `diesel` macros assume that all `diesel` macros have been brought into scope, and would generate something like `#[derive(Identifiable)]` instead of `#[derive(diesel::Identifiable)]`.

Nevertheless, personally I (and probably other people too) would create a subcrate in the workspace only for the diesel schema, so as not to corrupt my symbol scope with diesel derive macros, and it is obvious not to use this clippy lint in such a schema subcrate. So, this is probably not a critical problem.
