### ISSUE TITLE
Dead Links in CONTRIBUTING.md and other resources

### ISSUE THREAD

**Issue by JarredAllen** [rust-lang/rust-clippy#5268]
There are a large number of links to API docs in the [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) file and other pages linked from there which no longer work.

As best I can tell, these are the pages that have broken links:

- [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)
- [Docs for adding lints](../blob/master/doc/adding_lints.md)

Those pages would be substantially more helpful if all the dead API links were updated to point at the correct URLs.

**Comment by flip1995** [comment]
So `CONTRIBUTING.md` is pretty outdated. Some notes here:

> the `nodes in the AST docs`

broken link

> Clippy is a rustc compiler plugin. The main entry point is at src/lib.rs. In there, the lint registration is delegated to the clippy_lints crate.

not correct anymore

>`clippy_lints/src/lib.rs` imports all the different lint modules

should point to the file on the master branch

> and registers them with the rustc plugin registry. For example, the else_if_without_else lint is registered like this:

not true anymore -> registers in the `LintStore` now. example needs an update.

> The plugin::PluginRegistry provides two methods to register lints: register_early_lint_pass and register_late_lint_pass.

This is now done with the `LintStore` (links are therefore broken)

> you don't have to add anything by hand

Not completely true. You still have to register the lints.

> You can use rustup-toolchain-install-master to do that:

This example should point to the `./setup-toolchain.sh` script

> We use a bot powered by Homu

We should link to the rust-lang/homu project

> All code in this repository is under the Apache-2.0 or the MIT license.

Apache link broken

**Comment by flip1995** [comment]
On the `adding_lints.md` documentation:

> Currently this test will fail. If you go through the output you will see that we are told that clippy::foo_functions is an unknown lint, which is expected.

I'm not sure if this is true. With the `cargo dev new_lint` command the lint is defined properly, but no `LintPass` is registered for it. So the test might succeed, while no output is generated, no matter what we putt in the `LintPass`

> To change this behavior add // compile-flags: --edition 2018 at the top of the test file.

Meanwhile, this can be done with `// edition: 2018`

>This should fix the unknown clippy lint: clippy::foo_functions error that we saw when we executed our tests the first time.

See above

>The next decision we have to make is which lint pass our lint is going to need.

This sentence can be removed, since this decision is already addressed in the beginning. Maybe we should also move the `Lint Passes` section in a separate document and link to it at the beginning.

>  It boils down to using either EarlyLintPass or LateLintPass.

> We implement the check_fn method from the EarlyLintPass trait.

broken links


> Using the check_fn method gives us access to FnKind that has two relevant variants for us FnKind::ItemFn and FnKind::Method. Both provide access to the name of the function/method via an Ident.

Broken links, and should be revisited, since I think the signature of `check_fn` has changed recently.

> In our example, is_foo_fn looks like:

Same with this example

> The quickest way to use it, is the Rust playground: play.rust-lang.org

Maybe link to an example witch uses the author lint, like 2 lines below

>  you can use the dbg! macro anywhere in your code

link to the debug macro

> For EarlyLintPass lints:

> For LateLintPass lints:

broken links

> to ask on Discord, IRC or in the issue/PR.

Does Clippy still uses IRC? I don't think so.


---

Additional notes:

- Maybe we should simplify the Testing section and only put the most important information there, and create a new document for edition tests, rust fix tests, ...
