### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by CreepySkeleton** [rust-lang/rust-clippy#5270]
Hey guys, it looks like there wasn't a release of `clippy` in a few months already. Would it be possible to publish a new version?

**Comment by matthiaskrgr** [comment]
Hi, clippy is no longer published to crates.io.

Nowadays clippy is distributed over `rustup` (which you might already use to get the rust compiler).
In this case, you can install clippy via `rustup component add clippy`.
`rustup update` will then update both, clippy and the compiler if updates are available for both.

**Comment by CreepySkeleton** [comment]
What I meant was that the latest clippy shipped with cargo had been released few months ago:
```
$ cargo clippy -V
clippy 0.0.212 (69f99e74 2019-12-14)
```

But the most recent `rustc` was released a week ago
```
$ rustc -V
rustc 1.41.1 (f3e1a954d 2020-02-24)
```

Everything's up to date as far as I can tell:
```
$ rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: checking for self-updates

   stable-x86_64-pc-windows-msvc unchanged - rustc 1.41.1 (f3e1a954d 2020-02-24)
  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.43.0-nightly (75cf41afb 2020-03-04)

info: cleaning up downloads & tmp directories
```

**Comment by flip1995** [comment]
The Clippy version was not updated in the point release of rust 1.41.1, so it is still the 69f99e74 commit.

See this Clippy release: https://github.com/rust-lang/rust-clippy/releases/tag/rust-1.41.1

If you want a more recent Clippy, you can use the nightly or beta toolchain.

**Comment by Cypher1** [comment]
Can someone link me to the issue where it was decided to not ship to crates.io anymore? I used to be able to build from source using `cargo install` and rustup doesn't support my platform

**Comment by flip1995** [comment]
You can still install Clippy from source. For this see our [documentation](https://github.com/rust-lang/rust-clippy/blob/master/doc/basics.md#install-from-source).

There's not a real issue about this. Since Clippy got distributed via rustup, publishing it on crates.io doesn't make sense for us. The PR where we stopped publishing is #3247

**Comment by Cypher1** [comment]
Sure, but before it was easy, now I'm going to have to do a multistep process because having two ways to install it was a boy odd? There's probably more to it than that but it's annoying when something that used to work stops working without a clear reason for the lack of support

**Comment by Cypher1** [comment]
It also looks like the rust-clippy build script only works with the nightly compiler, can you confirm this?

**Comment by matthiaskrgr** [comment]
Yes, but you were never able to build "any" version of clippy with "any" version of the compiler I think.
Nightly clippy builds used to break all the time back then.

The nighty version that the repo is guaranteed to build with is set via the `rust-toolchain` file.

**Comment by Cypher1** [comment]
I've checked out rust-clippy's stable tag, removed the nightly only flags (as I don't have a nightly compiler), and now I'm directed to use rustup for get additional sources.
Is my only avenue forward (back to the workflow I had previously) to build significant chunks of rust from source?

Please don't understand me as saying it's wrong to tie clippy to rustup. I'm not, it might make sense for the project and most users. Still, I'd just like to know what benefit clippy gets from changing how it ships

**Comment by matthiaskrgr** [comment]
Clippy is kind of tied to the compiler. Cippy asks the compiler for its representation of the code, runs some lints, returns the results back to the compiler and then rustc prints the lint warnings that we all love.

So clippy directly uses a bunch of rustcs compiler internal APIs/functions/data structures etc.
Since the compiler changes rapidly, this previously meant that clippys code needed to be updated  continuously by the clippy team to match the rustc api (otherwise clippy would simply not compile).
Back at this time, clippy binary would be unavailable for days from nightly rustc from time to time.

At some point we got fed up and added a copy of clippy to the rustc source tree, so now when someone changes rustc code, they can fix the incompatibility with clippy at the same time, so that the rustc api and the in-source clippy stay in sync and clippy compiles stably all the time.

Every couple of weeks, the api compatibility fixes that went into the clippy-rustc are merged into this github repo and the new lints or fixes that were made to clippy in this repo are synced back into the rustc repo.
This can look like this:  https://github.com/rust-lang/rust/commit/f1a779c9a461652719a183d61002da2a7ab75113#diff-ecc74b126edfb289f95b6a04969f6adc10f10bbe207c2073ebf356fa1612a3c1

Inside this repo, after each sync from the rustc we pin the nightly to the rustc nightly that we synced from (with the rust-toolchain file) to make sure contributors can build and test clippy. 

I hope this gives some rough overview, please correct me if I am wrong :slightly_smiling_face:

**Comment by flip1995** [comment]
So IIUC you only have a stable `rustc` and no rustup? I assume you have access to cargo? On what target are you trying to build Clippy? With that information I may be able to give you a better suggestion on how to move forward.

**Comment by Cypher1** [comment]
Thank you! That explains it and is really helpful to understand.

You're right, I have a stable rustc and cargo which are patched by the
Termux maintainers to run on 'aarch64-linux-android', but there's no
patched rustup at the moment. It seems like a big job to get rustup to
support a new arch, and though the generic aarch64 might work, I haven't
been able to get rustup to try to use it.

Thanks for your help so far.

**Comment by flip1995** [comment]
Thanks for the information! `aarch64-linux-android` is a [Tier 2 platform without host tools](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2), which means, that the rust project currently doesn't ship any tools and with that also doesn't ship `rustc-dev`, which is required to compile Clippy. So the only way to natively compile Clippy for `aarch64-linux-android` is to compile rustc itself and with that Clippy. You can do this in `rust-lang/rust` with `./x.py build src/tools/clippy`.

This might take a while though. You may want to try to cross-compile Clippy. Out of interest I tried to do this and those are the steps that I came up with:

0. Have access to a machine which has at least Tier 2 with host tools support and where the Android NDK is available
1. Download the Android NDK: https://developer.android.com/ndk/downloads
    a. `export PATH=/path/to/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH`
2. Install the aarch64-linux-android target with `rustup target add aarch64-linux-android`
3. In the Clippy repo, run: `cargo dev setup intellij --repo-path=/path/to/rust` and move the added dependencies from `cfg(NOT_A_PLATFORM)` to normal deps.
4. Add the following lines to `.cargo/config.toml`:
    ```toml
    [target.aarch64-linux-android]
    linker = "/path/to/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
    ```
5. Build Clippy with `RUSTC_INSTALL_BINDIR=bin CFG_RELEASE_CHANNEL=nightly CFG_RELEASE=1.59.0 cargo build --target=aarch64-linux-android --release` (during linking it might look for `-lgcc`. You can work around this error by adding a `libgcc.a` textfile with the content `INPUT(-lunwind)` to `/path/to/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android`)

---

Note: It would also not help you, if Clippy would still be available on crates.io. The blocker is, that you don't have access to the `rustc-dev` component.

**Comment by Cypher1** [comment]
Yes, I understand the tier situation.

Thanks for exploring the steps but I hope it's clear how distributing
things through anything other than cargo seems significantly worse for
users who aren't always on fully supported platforms.

I mean, that's kinda what being unsupported is, so it's a cost benefit
analysis thing. Totally understand if it's too costly to do, just galling
for me that it used to work so nicely and now it seems out of reach.

I think, at this point, it'd be more practical for me to remote in to a
server and work there, or just give up on the fun of being able to work on
anything but a laptop.

Thanks for the help though. Hope it hasn't been a drag to walk me through
it all.

**Comment by flip1995** [comment]
> I mean, that's kinda what being unsupported is, so it's a cost benefit analysis thing. 

Yeah, you could make the case to add host tool support to aarch64-linux-android in rust-lang/rust. Though I don't know how much work that would be.

> Totally understand if it's too costly to do, just galling for me that it used to work so nicely and now it seems out of reach.

It would surprise me if there would be any difference if we'd publish it on crates.io. "used to work so nicely" must be years ago, where all the rustc_* crates were still shipped in rust-std: https://github.com/rust-lang/rust/pull/64823. 


> Thanks for the help though. Hope it hasn't been a drag to walk me through it all.

Not at all!
