### ISSUE TITLE
Enhance macro_use_imports lint with a auto applicable suggstion

### ISSUE THREAD

**Issue by flip1995** [rust-lang/rust-clippy#5275]
The `macro_use_imports` lint was implemented in #5230, but is currently missing a auto applicable suggestion. For this suggestion, every macro used in the module would have been detected and from this set of macros, a suggestion has to be build.

**Comment by DevinR528** [comment]
I have made a rough start on this [here](https://github.com/DevinR528/rust-clippy/blob/macro-use-sugg/clippy_lints/src/macro_use.rs). I had a few questions.
What do we do with re exported paths such as `println` from `std::prelude` the macro is from `std::macros` which is private? this isn't a great example since not many would explicitly import std::prelude but I'd imagine it holds true for other crates

If the import is only the crate name (no more `::mod::mod) because macros float to the top level is it safe to assume `crate::macro` is always valid?

I'm sure there are other things I'm not doing correctly, should I move this to a PR?

**Comment by flip1995** [comment]
I must admit, that I don't really know, how I would handle this.

I think that `crate::macro` can still be a reexport from a private module of `crate`. It will definitely need extensive testing, including macros from sub crates, similar to 
https://github.com/rust-lang/rust-clippy/blob/3d0f0e33aff4f5d916ec286bc586935d767c3cfc/tests/ui/wildcard_imports.rs#L1-L8

What I would suggest is to first write a huge test base, with every case you can think of, and then work from there. If you have an idea for a test case, but don't know how to implement it in the Clippy test suite, you can open a PR, and we can work it out together.
