### ISSUE TITLE
match_on_vec_items: False positives with indexing after `Read::read_exact`

### ISSUE THREAD

**Issue by psychon** [rust-lang/rust-clippy#5553]
A new clippy error message  occurred in the Travos build of x11rb with nightly rust. I think that these are two false positives.

Travis build: https://travis-ci.org/github/psychon/x11rb/jobs/681967167

There are two cases of "indexing into a vector may panic" aka `match_on_vec_items`.

First one occurs here:
https://github.com/psychon/x11rb/blob/56486c63d1d960afbd75debb4d85db2d4148a0ef/src/rust_connection/mod.rs#L497-L503
At the time of `match buffer[0]`, the `Vec` `buffer` is guaranteed to have length 32 (even though it is mutable - there are always at least 32 bytes in a packet and these include a length field that tells us how many more bytes are coming).

The second occurrence is basically identical to the first one:
https://github.com/psychon/x11rb/blob/56486c63d1d960afbd75debb4d85db2d4148a0ef/src/rust_connection/mod.rs#L551-L559

I could handle this by using `get(0)` as suggested by clippy. However, that only makes the code more complicated. Alternatively, I could `#[allow]` the lint, which is also not really a good solution. Basically: I feel like this suggestion is not a good one. However, feel free to disagree with me here and keep things the way they are. Fine with me.

I saw #5551, but I feel like this is a different issue. In #5551, the `Vec` is not mutable, so its length is guaranteed to be large enough. Here, the `Vec` is mutable, but not mutated (yet) at the time the indexing happens.

**Comment by flip1995** [comment]
I think allowing this lint here would add the information that this is really intended and that it 100% doesn't panic. The (most) Rusty thing to do in those cases would be to write ``buffer.get(0).expect("why this can't ever be `None`"``. But I can see that this is too verbose for people, which is why the lint suggesting this (`indexing_slicing`) is `pedantic`.

The underlying issue can't be fixed, since Clippy can't ever know the context or the programmers intention.

---

@phansch Should we move the `match_on_vec_items` to `pedantic` (currently `correctness`)?

**Comment by flip1995** [comment]
Well you could also add a `None => unreachable!("why?")` to clarify this.
