### ISSUE TITLE
New Lint: Needless Type Annotation

### ISSUE THREAD

**Issue by seanchen1991** [rust-lang/rust-clippy#5606]
Similar to needless_lifetimes, except for type annotations. Essentially, if the type inferencer infers a type that matches an explicitly-annotated type, then the annotation can be removed. 

Admittedly, I don't think there is a strong "Why is this bad" case to be made for explicit type annotations, but it would be useful as a way to remove explicit type annotations as Rust's inferencer gets smarter over time. 

Lint name idea: needless_type_annotation

**Comment by seanchen1991** [comment]
Is there a general roadmap for how this could be implemented? How difficult would be it be?

**Comment by flip1995** [comment]
I marked it as hard, since I don't think, that there is any way in the compiler to determine, if a type could have been inferred. If a type is defined by the user, the compiler assumes this is the ground truth for the type and this is also represented that way by the intermediate representations. See [`rustc_hir::TyKind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.TyKind.html).

Maybe a check could look for type definitions, remove them and try to infer the type afterwards. But that would mean to run the type checker multiple times, which isn't really viable.

Maybe there are compiler internals, that would simplify the implementation of this lint, but you would have to ask the compiler folk on discord or zulip about that.

**Comment by matthiaskrgr** [comment]
I think it would be quite a bit annoyed if I start coding on something, remove some type annotations here and there according to clippy suggestions, but later I need to re-add them in order to get `foo.into()` to work in some places.

I feel like something like
`let x: Foo = something().into();`
would just become `let x = something().to_Foo();` with this lint.. :/.

Of course `let s: String = String::from("hello world");` is overkill and could just be `let s = ..` but I think that `Explicit`[might be]`better than implicit` in quite a few cases which will probably be hard to get right in a lint.

**Comment by seanchen1991** [comment]
Yea, I kind of realized that this probably isn't as helpful as I thought it would be. Plus the fact that it would result in a performance regression since the inferencer would now have to run over every type regardless of whether it was explicitly annotated or not means that the amount of work required for this small win doesn't seem worth it.
