### ISSUE TITLE
rustc_driver::run_compiler needs 5 arguments rather than 4.

### ISSUE THREAD

**Issue by longlb** [rust-lang/rust-clippy#6095]
I had this error come up while I was trying to compile the base repo. I checked the online documentation as well and it still only shows a need for 4 arguments. Is this because of a compiler problem or am I missing some packages?

```Compiling clippy v0.0.212 (/home/longlb/projects/rust-clippy)
error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src/driver.rs:360:20
    |
360 |             return rustc_driver::run_compiler(&args, &mut DefaultCallbacks, None, None);
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ -----  ---------------------  ----  ---- supplied 4 arguments
    |                    |
    |                    expected 5 arguments

error[E0061]: this function takes 5 arguments but 4 arguments were supplied
   --> src/driver.rs:423:9
    |
423 |         rustc_driver::run_compiler(&args, callbacks, None, None)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^ -----  ---------  ----  ---- supplied 4 arguments
    |         |
    |         expected 5 arguments

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0061`.
error: could not compile `clippy`
```

**Comment by ebroto** [comment]
Hey, thanks for the heads-up!  A fix is coming :) (#6094)

As Clippy is built against the master branch of rustc, whenever changes in rustc break Clippy, this happens. 
Currently Clippy gets fixed in-tree in the rustc repo, but those changes have to be synced back to this repo. We are working on avoiding this hassle to contributors by pinning to a nightly; this will be unblocked with the next release of rustup.
