### ISSUE TITLE
Keep the hacktoberfest topic in the repo for a while longer

### ISSUE THREAD

**Issue by cauebs** [rust-lang/rust-clippy#6322]
Last month I started contributing because of hacktoberfest and, besides having learned a lot, I also like to believe I was effectively helpful.

Some conditions for PRs to count towards the prize (a cool t-shirt that most of us like to collect) require the repo to be marked with the `hacktoberfest` topic, which it was. I'm hoping it could be brought back, just for this month while we wrap things up.

**Comment by cauebs** [comment]
Actually, it seems it is not possible to undo this.

https://github.com/digitalocean/hacktoberfest/issues/724

**Comment by flip1995** [comment]
Oh, sorry about that. I was told that PRs had to be accepted during October and then thought removing the hacktoberfest topic  was safe to do in November. I removed the topic 5 (?) days ago. Basically, everything that was said in this comment https://github.com/digitalocean/hacktoberfest/issues/724#issuecomment-721728367 is what I think about this situation.

Again, I'm really sorry for everyone who contributed to Clippy during hacktoberfest and now miss out on the rewards because of this. But I consider this a major flaw in the hacktoberfest rules / application of them.

Please don't spam your critic about this in the above posted hacktoberfest issue. Emailing them with that exact feedback could help though: hacktoberfest@digitalocean.com

**Comment by cauebs** [comment]
@flip1995 Totally not your fault. I expected it to be like that as well. But it's ok, let's not be mean to the people organizing this. It was an honest mistake and I believe it will work better next year.

The main objective, which was incentivizing people like me to contribute, was accomplished (even though I was tricked into it! hahah). Thanks for your work, and I hope I find the time to continue contributing ;)

**Comment by flip1995** [comment]
> let's not be mean to the people organizing this

Definitely not, those people are awesome for making this possible!

> even though I was tricked into it! hahah

Let me know, how I can trick you into contributing even more 😜
