### ISSUE TITLE
Lint transmute where source type is unspecified.

### ISSUE THREAD

**Issue by ticki** [rust-lang/rust-clippy#715]
This is an easy way to create UB. For example:

``` rust
unsafe {
    let bytes = [0u8; 4];
    let num = *mem::transmute<_, &u32>(bytes);
}
```

The error (resulting in segfault) might be a little hard to spot. The problem is that the array is transmuted into a null pointer. The transmute argument should be `&bytes` instead.

By forcing the programmer to add type annotations, he or she is not as likely to commit this mistake (since it will be catched during type checking):

``` rust
unsafe {
    let bytes = [0; 4];
    let num = *mem::transmute<&[u8; 4], &u32>(&bytes);
}
```

Since this is a major source of bugs resulting in UB, I propose adding a lint being `deny` by default, which forces the programmer to annotate the type.

**Comment by Manishearth** [comment]
I'm against `deny` lints for anything that isn't outright wrong.

Also, your code above won't compile due to the size requirement on transmute. I don't think annotations are explicitly necessary due to this requirement. Given this I'd actually prefer `allow`, but am okay with `warn`.

**Comment by Ticki** [comment]
Oh, yeah. The code is wrong, but the idea is right. This is an issue, I've dealt with multiple times. I have found explicit notation to help a lot on these errors.

Maybe `deny` is too much? `warn` would be fine. I think `allow` would be a little misplaced, since this is actually something that can lead to UB and/or logic errors.
