### ISSUE TITLE
Suggest casting bool to int instead of using if statement.

### ISSUE THREAD

**Issue by cwhakes** [rust-lang/rust-clippy#8131]
### What it does

Instead of using an if statement to convert a bool to an int, this lint suggests using a coercion or a `from()` function.

### Lint Name

bool_to_int_with_if

### Category

style

### Advantage

- Makes code more concise
- Makes this conversion more discoverable

### Drawbacks

- None

### Example

```rust
if condition {
    1_i64
} else {
    0
}
```

Could be written as:

```rust
i64::from(condition)
```

or

```rust
condition as i64
```

**Comment by xFrednet** [comment]
Hey, @bsimon12, I've unassigned you from this issue, since it has been a long time since you've claimed it. If you want to continue work on this or select another good-first-issue you can always claim it again :upside_down_face:

**Comment by jst-r** [comment]
I've mostly finished working on it.

It's not quite clear to me whether to include both `as` and `from` as suggestions?

Also, it seem like dealing with parenthesis around condition in `as` coercion is not trivial. Is it okay to always include them?
Exsample 
```rust
// parenthesis needed because coercion has higher priority than boolean operations
let x = if a || b { 1 } { 0 };
// fixed
let x = (a || b) as usize;
// fixed without parenthesis
let x = a || b as usize; // error[[E0308]]: mismatched types

// parenthesis not needed
let x = if a { 1 } { 0 };
// fixed with parenthesis
let x = (a) as usize; // not ideal
```

**Comment by xFrednet** [comment]
Hey @jst-r, thanks for picking this up!


> It's not quite clear to me whether to include both as and from as suggestions?

It depends on if you want to make the suggestion automatically applicable. Then it would be better to only emit one suggestion. I would suggest only using `from()` as that would also solve the parenthesis problem. `<ty>::from(<expr>)` should always work, while `<expr> as <ty>` might require parenthesis, as you've mentioned.

If you want to take the extra step, and create an `as` suggestion, you can look at the parent/child expressions of nodes to figure out if you need the parenthesis. But that is probably more complicated than it needs to be :upside_down_face:

**Comment by jst-r** [comment]
Thanks for suggestion, @xFrednet !

I've already implemented automatically applicable version (I hate when I can't just ctrl+. to fix something). To do so I've commented `as` suggestion out.

I feel like trying to decide if parenthesis are needed would have a lot of edge cases. And as a consequence possible bugs.

After running dogfood test, I think `.into()` conversion would be more concise and (imho) more readable.
For example returning from function using `has_own.into()` feels less noisy than `usize::from(has_own)`.

But it comes with the same challenge as `as`. And type inference seems flaky at times.
Example: `let x: i32 = 1i32 + (a || b).into();` doesn't compile on stable.
It probably can be fixed by some checks on parent nodes.

I'm not sure I'll be able to handle all the cases. But `.into()` seems like a good thing to suggest. 
Always suggesting `from` and adding a note about `into` may be a reasonable middle ground.

What do you think about it?

**Comment by jst-r** [comment]
I get why why you prefer `as <ty>`. After giving it a little more thought, `as` feels both as explicit as `from` and isn't too noisy.

> As a simple fix, you could check if the boolean expression is a Path/Method/Function/Array expression and otherwise suggest parenthesis.
I haven't thought about it. It's definitely not too hard.

I'll implement version with `as`. And, hopefully, will open a PR tomorrow.

**Comment by jst-r** [comment]
Looks like it was even simpler than that. After looking at precedence, I found that all the operators/expressions that have higher precedence can't have `if` statement in them. Well, it can be, if is const expression and is wrapped in generic paremeter.

```rust
check.precedence().order() < ExprPrecedence::Cast.order()
```
Seems to work correctly.

**Comment by jst-r** [comment]
Looks like it was even simpler than that. After looking at precedence, I found that all the operators/expressions that have higher precedence can't have `if` statement in them. Well, it can be, if is const expression and is wrapped in generic paremeter.

```rust
check.precedence().order() < ExprPrecedence::Cast.order()
```
Seems to work correctly.

But `cast_lossless` lints the result.
In my opinion it is a problem with cast_lossless, since bool already holds smallest possible amount of information. Thus the only lossy coercion from bool would be to unit.

Should I roll it back to `from` or think about changing `cast_lossless` to check if coercion actually lossless?

**Comment by xFrednet** [comment]
Perfect, I didn't know that rustc offers something like this directly :+1: 

Agreed, that sounds like a FP in `cast_lossless`. Well, as long as `cast_lossless` isn't fixed, I would suggest using `from`. If you have the time and want to fix `cast_lossless` as well, that would also be cool.

I don't actually know if there is a consensus, if `as` is better than `from` or the other way around :sweat_smile:

**Comment by jst-r** [comment]
I've opened PR with `from` suggestion.

Should I open a issue about `cast_lossless`?

**Comment by xFrednet** [comment]
Awesome!

> Should I open a issue about `cast_lossless`?

If you have the time that would be good. I believe it works for other numeric types, like `u8 as u32` is fine. At least I remember seeing a PR like that some time ago. :upside_down_face:

**Comment by Xaeroxe** [comment]
I'm enhancing this lint in #9476 such that it will also catch code like

```rust
if a {
    0
} else {
    1
}
```

**Comment by conradludgate** [comment]
My 2c. I don't feel like this is idiomatic and I feel this should have been nominated for pedantic before going strait into style. Several others I have spoken with find this _more confusing_ than using the if-else ternary operator

**Comment by robbert-vdh** [comment]
I agree. I find `if foo.bar() > 4 { 1 } else { 0 }` to be much more readable than the `i32::from(foo.bar() > 4)` suggested by this lint, especially when `if foo.bar() > 4 { 0 } else { 1 }` becomes `i32::from(foo.bar() <= 4)`.

**Comment by xFrednet** [comment]
It's hard to judge in which category a lint belongs. For me, it took some getting used to, but now I prefer the `i32::from(<bool>)` a bit. That being said, we can definitely move the lint to `pedantic`. We can backport the change to beta, then it'll only take a release until the change comes into effect on stable. Would that be fine with everyone?

**Comment by cwhakes** [comment]
I'd prefer it to remain in `style` to aid in discoverability and to circumvent people wondering whether `if condition { 1 } else { 0 }` is really branchless. However, moving it to `pedantic` wouldn't be the end of the world, and I only casually object.
