### ISSUE TITLE
We should extend `--explain` to include config options

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#9990]
Clippy has an `--explain` command to display the lint documentation in the console. Ideally, we'd like to expand the command to include the configurations, which effect the lint emission. This is already done for [Clippy's lint list](https://rust-lang.github.io/rust-clippy/master/index.html).

Here is an example for such a lint: [borrow_as_ptr](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr)

This implementation could take inspiration from how we collect the metadata for our lint list:

https://github.com/rust-lang/rust-clippy/blob/3cf2c17e53d115bd8c233a268c0d0ff0fbb2395e/clippy_lints/src/utils/internal_lints/metadata_collector.rs#L162

CC: #9880

**Comment by blyxyas** [comment]
This would require moving [`metadata_collector.rs`](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/utils/internal_lints/metadata_collector.rs) out of `internal_lints` and removing [this `#[cfg]` feature check](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/utils/conf.rs#L169).

Btw, why does this feature (`internal`) exists? `rustup` downloads compiled artifacts, so unused code gets removed AFAIK.

If the feature exists because of compile-times, maybe we should remove it as between times from `cargo build --features internal` to `cargo build` there's only a 1.4% difference (in my machine). I think that's negligible.

**Comment by xFrednet** [comment]
It would be good if we could find a way, to connect the data without enabling all internal lints. But this can include enabling some code from the *metadata collection monster* by default. This mainly involves connecting the configs to the lint documentation and should be relatively simple. 

> Btw, why does this feature (`internal`) exists?

I'm not 100% sure, but my guess is a combination of these factors:
* Performance and size, these lints should never detect code outside of Clippy, so they would just waste time and disk space for other projects
* Errors, internal lints are generally less tested than normal lints, which increases the chance of ICEs
* Maybe dependencies?

> [`metadata_collector.rs`](https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/utils/internal_lints/metadata_collector.rs?rgh-link-date=2023-04-22T23%3A06%3A25Z)

The metadata collection monster was the first bigger project I worked on in Clippy/rust-lang. Looking at the code takes me back. I also love how it was okay to have more stupid comments in that code :D
