### ISSUE TITLE
Document lint configuration values in Clippy's book

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#9991]
We have a few lints with configuration values, like [borrow_as_ptr](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr). We want to increase the visibility of these config values, to encourage the use of them.

As part of this, we'd like a chapter about configuring lints and having a list of available configurations with links to [Clippy's lint list](https://rust-lang.github.io/rust-clippy/master/index.html).

Tasks:
* [x] Write how a user can add configurations: See [Current docs](https://github.com/rust-lang/rust-clippy#configuration)
* [x] Generate list of configurations. This can be done in Clippy's metadata collector. https://github.com/rust-lang/rust-clippy/blob/master/clippy_lints/src/utils/internal_lints/metadata_collector.rs
* [x] Include the generated list in the book
* [x] Be happy!

---

I'm open to mentoring this issue :)

CC: #9880

**Comment by tylerjw** [comment]
@rustbot claim

I want to work on this issue. This will be my second PR. Thank you for all the help on the first one.

**Comment by xFrednet** [comment]
Awesome! Please reach out if you need any assistance :)

**Comment by tylerjw** [comment]
On the first task; here is what is in the README:

![image](https://user-images.githubusercontent.com/2490389/211202872-3536e05f-0508-4299-b31c-7083e3458b68.png)

Would you like something different than this?

**Comment by tylerjw** [comment]
This is also in the book:

![image](https://user-images.githubusercontent.com/2490389/211203093-5096c20a-e647-4d1b-8953-e3967605ea35.png)

https://doc.rust-lang.org/nightly/clippy/configuration.html

**Comment by tylerjw** [comment]
Are you hoping for something similar to what is in the rustc book here: https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html

**Comment by tylerjw** [comment]
I'm sorry for being slow about working on this. Just so I understand, this syntax you are showing with `".."`:

```
disallowed-names = ["today"] # -> ["today"]
disallowed-names = ["tomorrow", ".."] # -> ["tomorrow", "today"]
```

Can you explain a situation where this would be helpful? Is there a way for one project to inherit the clippy config of another and then extend it?

**Comment by tylerjw** [comment]
@xFrednet I'm still working on the learning I need to do in order to make the more significant PR to the book but in the meantime I documented the config behavior you noted in your comment here: https://github.com/rust-lang/rust-clippy/pull/10190

**Comment by tylerjw** [comment]
As to `cognitive-complexity-threshold` I see it is in the nursery, and there are a few issues where people comment that it is not well documented. Should I just remove the mention of it from the docs here?

**Comment by tylerjw** [comment]
Here is a PR with both the change to remove `cognitive-complexity-threshold` and add a note about extending default values: https://github.com/rust-lang/rust-clippy/pull/10199

**Comment by tylerjw** [comment]
I have two ideas for approaches here. Let me know which one you think I should pursue.

- New `cargo dev` command that converts `lints.json` to a markdown page for the book.
- metadata collector now outputs markdown for the book

The first is nice because it should be easy enough to run independently. It would depend on de-serializing the json file (which would make it depend on the structure from metadata collector staying the same). The primary downside here being that I'd be taking the `docs` string from the json which is already markdown formatted for generating the lints page and parsing it. This means that I'd depend on the structure of that string. I'm unsure how stable the structure of that string is or how confusing it would be to update this workflow if it ever changed.

The second is nice because metadata collector internally has all the information I need to generate this docs page and the CI system is already running it when deploying the websites. The downside I see to this is now metadata collector has two outputs and that might confuse some people.

Do you have any other ideas of how this should be done?


Here is my draft idea for the new config page in the docs:

## Configuration Options

These are the list of configuration options that can be placed in `clippy.toml` or `.clippy.toml` and the lints they affect.

| Config | Type             | Default | Description                                        | Lints                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|--|--|--|--|--|
| `msrv` | `Option<String>` | `None`  | The minimum rust version that the project supports | [approx_constant](https://rust-lang.github.io/rust-clippy/master/index.html#approx_constant)  [borrow_as_ptr]( https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr )  [cast_abs_to_unsigned]( https://rust-lang.github.io/rust-clippy/master/index.html#cast_abs_to_unsigned )  [checked_conversions]( https://rust-lang.github.io/rust-clippy/master/index.html#checked_conversions )  [cloned_instead_of_copied]( https://rust-lang.github.io/rust-clippy/master/index.html#cloned_instead_of_copied )  [deprecated_cfg_attr]( https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_cfg_attr ) [err_expect]( https://rust-lang.github.io/rust-clippy/master/index.html#err_expect ) [filter_map_next]( https://rust-lang.github.io/rust-clippy/master/index.html#filter_map_next ) [from_over_into]( https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into ) [if_then_some_else]( https://rust-lang.github.io/rust-clippy/master/index.html#if_then_some_else ) [index_refutable_slice]( https://rust-lang.github.io/rust-clippy/master/index.html#index_refutable_slice ) [manual_bits]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_bits ) [manual_clamp]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_clamp ) [manual_let_else]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_let_else ) [manual_non_exhaustive]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_non_exhaustive ) [manual_range_contains]( https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_cfg_attr ) [manual_split_once]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_split_once ) [manual_str_repeat]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_str_repeat ) [manual_strip]( https://rust-lang.github.io/rust-clippy/master/index.html#manual_strip ) [map_clone]( https://rust-lang.github.io/rust-clippy/master/index.html#map_clone ) [map_unwrap_or]( https://rust-lang.github.io/rust-clippy/master/index.html#map_unwrap_or ) [match_like_matches_macro]( https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro ) [mem_replace_with_default]( https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_with_default ) [missing_const_for_fn]( https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn ) [option_as_ref_deref]( https://rust-lang.github.io/rust-clippy/master/index.html#option_as_ref_deref ) [ptr_as_ptr]( https://rust-lang.github.io/rust-clippy/master/index.html#ptr_as_ptr ) [redundant_field_names]( https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names ) [redundant_static_lifetimes]( https://rust-lang.github.io/rust-clippy/master/index.html#redundant_static_lifetimes ) [unchecked_duration_subtraction]( https://rust-lang.github.io/rust-clippy/master/index.html#unchecked_duration_subtraction ) [uninlined_format_args]( https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args ) [unnested_or_patterns]( https://rust-lang.github.io/rust-clippy/master/index.html#deprecated_cfg_attr ) [use_self]( https://rust-lang.github.io/rust-clippy/master/index.html#use_self ) |
| ...    |                  |         |                                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

**Comment by xFrednet** [comment]
I saw this comment before the PR. ^^

The output looks really cool. The only NIT is that I'd like the description column to be wider than it currently is. Maybe we can add `<br>` behind each lint name and config element? The question is also if we can have paragraphs. It might actually be better to have them more layout like this:

---

## <config-name>

<description>

<default>

<lints>

---

Even though I like the table look of your suggestion a lot. Would you be okay with creating a prototype for the example above? Then we can make screenshots and ask for more feedback on Zulip :)
